INSERT INTO preference ("resourceId", name, conf, "creatorId", "creatorName") VALUES

-- routes
((SELECT id FROM resource WHERE name = 'routes'), 'Default', '[
  {"key":"core",          "isVisible":true,  "defaultWidth":"60px"},
  {"key":"protected",     "isVisible":true,  "defaultWidth":"60px"},
  {"key":"id",            "isVisible":false},
  {"key":"serviceId",     "isVisible":false},
  {"key":"serviceName",   "isVisible":true},
  {"key":"resourceId",    "isVisible":false},
  {"key":"resourceName",  "isVisible":true},
  {"key":"name",          "isVisible":true},
  {"key":"description",   "isVisible":true},
  {"key":"pattern",       "isVisible":true},
  {"key":"operationId",   "isVisible":false},
  {"key":"operationName", "isVisible":true},
  {"key":"methodIds",     "isVisible":false},
  {"key":"methodNames",   "isVisible":true},
  {"key":"createdAt",     "isVisible":false},
  {"key":"creatorName",   "isVisible":false},
  {"key":"updatedAt",     "isVisible":false},
  {"key":"updaterName",   "isVisible":false},
  {"key":"archived",      "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",    "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'routes'), 'Compact', '[
  {"key":"core",          "isVisible":false, "defaultWidth":"60px"},
  {"key":"protected",     "isVisible":true,  "defaultWidth":"60px"},
  {"key":"id",            "isVisible":false},
  {"key":"serviceId",     "isVisible":false},
  {"key":"serviceName",   "isVisible":true},
  {"key":"resourceId",    "isVisible":false},
  {"key":"resourceName",  "isVisible":true},
  {"key":"name",          "isVisible":true},
  {"key":"description",   "isVisible":false},
  {"key":"pattern",       "isVisible":true},
  {"key":"operationId",   "isVisible":false},
  {"key":"operationName", "isVisible":true},
  {"key":"methodIds",     "isVisible":false},
  {"key":"methodNames",   "isVisible":true},
  {"key":"createdAt",     "isVisible":false},
  {"key":"creatorName",   "isVisible":false},
  {"key":"updatedAt",     "isVisible":false},
  {"key":"updaterName",   "isVisible":false},
  {"key":"archived",      "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",    "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'routes'), 'Archives', '[
  {"key":"core",          "isVisible":false, "defaultWidth":"60px"},
  {"key":"protected",     "isVisible":true,  "defaultWidth":"60px"},
  {"key":"id",            "isVisible":false},
  {"key":"serviceId",     "isVisible":false},
  {"key":"serviceName",   "isVisible":true},
  {"key":"resourceId",    "isVisible":false},
  {"key":"resourceName",  "isVisible":true},
  {"key":"name",          "isVisible":true},
  {"key":"description",   "isVisible":false},
  {"key":"pattern",       "isVisible":true},
  {"key":"operationId",   "isVisible":false},
  {"key":"operationName", "isVisible":true},
  {"key":"methodIds",     "isVisible":false},
  {"key":"methodNames",   "isVisible":true},
  {"key":"createdAt",     "isVisible":false},
  {"key":"creatorName",   "isVisible":false},
  {"key":"updatedAt",     "isVisible":false},
  {"key":"updaterName",   "isVisible":false},
  {"key":"archived",      "isVisible":true, "defaultWidth":"60px"},
  {"key":"archivedAt",    "isVisible":true}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'routes'), 'Audit', '[
  {"key":"core",          "isVisible":false, "defaultWidth":"60px"},
  {"key":"protected",     "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",            "isVisible":false},
  {"key":"serviceId",     "isVisible":false},
  {"key":"serviceName",   "isVisible":true},
  {"key":"resourceId",    "isVisible":false},
  {"key":"resourceName",  "isVisible":true},
  {"key":"name",          "isVisible":true},
  {"key":"description",   "isVisible":false},
  {"key":"pattern",       "isVisible":false},
  {"key":"operationId",   "isVisible":false},
  {"key":"operationName", "isVisible":false},
  {"key":"methodIds",     "isVisible":false},
  {"key":"methodNames",   "isVisible":false},
  {"key":"createdAt",     "isVisible":true},
  {"key":"creatorName",   "isVisible":true},
  {"key":"updatedAt",     "isVisible":true},
  {"key":"updaterName",   "isVisible":true},
  {"key":"archived",      "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",    "isVisible":false}
]', -1, 'system'),

-- consumers
((SELECT id FROM resource WHERE name = 'consumers'), 'Default', '[
  {"key":"id",           "isVisible":false},
  {"key":"userId",       "isVisible":true,  "defaultWidth":"80px"},
  {"key":"nickname",     "isVisible":true,  "defaultWidth":"100px"},
  {"key":"accessToken",  "isVisible":true, "defaultWidth":"300px"},
  {"key":"refreshToken", "isVisible":true, "defaultWidth":"300px"},
  {"key":"roles",        "isVisible":true},
  {"key":"createdAt",    "isVisible":false},
  {"key":"updatedAt",    "isVisible":false},
  {"key":"archived",     "isVisible":true, "defaultWidth":"60px"},
  {"key":"archivedAt",   "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'consumers'), 'Compact', '[
  {"key":"id",           "isVisible":false},
  {"key":"userId",       "isVisible":true,  "defaultWidth":"80px"},
  {"key":"nickname",     "isVisible":true,  "defaultWidth":"100px"},
  {"key":"accessToken",  "isVisible":false, "defaultWidth":"300px"},
  {"key":"refreshToken", "isVisible":false, "defaultWidth":"300px"},
  {"key":"roles",        "isVisible":true},
  {"key":"createdAt",    "isVisible":false},
  {"key":"updatedAt",    "isVisible":false},
  {"key":"archived",     "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",   "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'consumers'), 'Archives', '[
  {"key":"id",           "isVisible":false},
  {"key":"userId",       "isVisible":true,  "defaultWidth":"80px"},
  {"key":"nickname",     "isVisible":true,  "defaultWidth":"100px"},
  {"key":"accessToken",  "isVisible":false, "defaultWidth":"300px"},
  {"key":"refreshToken", "isVisible":false, "defaultWidth":"300px"},
  {"key":"roles",        "isVisible":true},
  {"key":"createdAt",    "isVisible":false},
  {"key":"updatedAt",    "isVisible":false},
  {"key":"archived",     "isVisible":true, "defaultWidth":"60px"},
  {"key":"archivedAt",   "isVisible":true}
]', -1, 'system'),

-- services
((SELECT id FROM resource WHERE name = 'services'), 'Default', '[
  {"key":"core",       "isVisible":true,  "defaultWidth":"60px"},
  {"key":"id",         "isVisible":false},
  {"key":"name",       "isVisible":true},
  {"key":"pattern",    "isVisible":true},
  {"key":"createdAt",  "isVisible":false},
  {"key":"creatorName","isVisible":false},
  {"key":"updatedAt",  "isVisible":false},
  {"key":"updaterName","isVisible":false},
  {"key":"archived",   "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt", "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'services'), 'Compact', '[
  {"key":"core",       "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",         "isVisible":false},
  {"key":"name",       "isVisible":true},
  {"key":"pattern",    "isVisible":true},
  {"key":"createdAt",  "isVisible":false},
  {"key":"creatorName","isVisible":false},
  {"key":"updatedAt",  "isVisible":false},
  {"key":"updaterName","isVisible":false},
  {"key":"archived",   "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt", "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'services'), 'Archives', '[
  {"key":"core",       "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",         "isVisible":false},
  {"key":"name",       "isVisible":true},
  {"key":"pattern",    "isVisible":true},
  {"key":"createdAt",  "isVisible":false},
  {"key":"creatorName","isVisible":false},
  {"key":"updatedAt",  "isVisible":false},
  {"key":"updaterName","isVisible":false},
  {"key":"archived",   "isVisible":true, "defaultWidth":"60px"},
  {"key":"archivedAt", "isVisible":true}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'services'), 'Audit', '[
  {"key":"core",       "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",         "isVisible":false},
  {"key":"name",       "isVisible":true},
  {"key":"pattern",    "isVisible":false},
  {"key":"createdAt",  "isVisible":true},
  {"key":"creatorName","isVisible":true},
  {"key":"updatedAt",  "isVisible":true},
  {"key":"updaterName","isVisible":true},
  {"key":"archived",   "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt", "isVisible":false}
]', -1, 'system'),

-- resources
((SELECT id FROM resource WHERE name = 'resources'), 'Default', '[
  {"key":"core",        "isVisible":true,  "defaultWidth":"60px"},
  {"key":"id",          "isVisible":false},
  {"key":"serviceId",   "isVisible":false},
  {"key":"serviceName", "isVisible":true},
  {"key":"name",        "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'resources'), 'Compact', '[
  {"key":"core",        "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",          "isVisible":false},
  {"key":"serviceId",   "isVisible":false},
  {"key":"serviceName", "isVisible":true},
  {"key":"name",        "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'resources'), 'Archives', '[
  {"key":"core",        "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",          "isVisible":false},
  {"key":"serviceId",   "isVisible":false},
  {"key":"serviceName", "isVisible":true},
  {"key":"name",        "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":true, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":true}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'resources'), 'Audit', '[
  {"key":"core",        "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",          "isVisible":false},
  {"key":"serviceId",   "isVisible":false},
  {"key":"serviceName", "isVisible":true},
  {"key":"name",        "isVisible":true},
  {"key":"createdAt",   "isVisible":true},
  {"key":"creatorName", "isVisible":true},
  {"key":"updatedAt",   "isVisible":true},
  {"key":"updaterName", "isVisible":true},
  {"key":"archived",    "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":false}
]', -1, 'system'),

-- cors
((SELECT id FROM resource WHERE name = 'cors'), 'Default', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":true},
  {"key":"credentials", "isVisible":true},
  {"key":"createdAt",  "isVisible":false},
  {"key":"creatorName","isVisible":false},
  {"key":"updatedAt",  "isVisible":false},
  {"key":"updaterName","isVisible":false},
  {"key":"archived",   "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt", "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'cors'), 'Compact', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":false},
  {"key":"credentials", "isVisible":false},
  {"key":"createdAt",  "isVisible":false},
  {"key":"creatorName","isVisible":false},
  {"key":"updatedAt",  "isVisible":false},
  {"key":"updaterName","isVisible":false},
  {"key":"archived",   "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt", "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'cors'), 'Archives', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":false},
  {"key":"credentials", "isVisible":false},
  {"key":"createdAt",  "isVisible":false},
  {"key":"creatorName","isVisible":false},
  {"key":"updatedAt",  "isVisible":false},
  {"key":"updaterName","isVisible":false},
  {"key":"archived",   "isVisible":true, "defaultWidth":"60px"},
  {"key":"archivedAt", "isVisible":true}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'cors'), 'Audit', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":false},
  {"key":"credentials", "isVisible":false},
  {"key":"createdAt",  "isVisible":true},
  {"key":"creatorName","isVisible":true},
  {"key":"updatedAt",  "isVisible":true},
  {"key":"updaterName","isVisible":true},
  {"key":"archived",   "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt", "isVisible":false}
]', -1, 'system'),

-- operations
((SELECT id FROM resource WHERE name = 'operations'), 'Default', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":true},
  {"key":"color",       "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'operations'), 'Compact', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'operations'), 'Archives', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":true, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":true}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'operations'), 'Audit', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":false},
  {"key":"createdAt",   "isVisible":true},
  {"key":"creatorName", "isVisible":true},
  {"key":"updatedAt",   "isVisible":true},
  {"key":"updaterName", "isVisible":true},
  {"key":"archived",    "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":false}
]', -1, 'system'),

-- fields
((SELECT id FROM resource WHERE name = 'fields'), 'Default', '[
  {"key":"core",         "isVisible":true,  "defaultWidth":"60px"},
  {"key":"id",           "isVisible":false},
  {"key":"serviceId",    "isVisible":false},
  {"key":"serviceName",  "isVisible":true},
  {"key":"resourceId",   "isVisible":false},
  {"key":"resourceName", "isVisible":true},
  {"key":"name",         "isVisible":true},
  {"key":"createdAt",    "isVisible":false},
  {"key":"creatorName",  "isVisible":false},
  {"key":"updatedAt",    "isVisible":false},
  {"key":"updaterName",  "isVisible":false},
  {"key":"archived",     "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",   "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'fields'), 'Compact', '[
  {"key":"core",         "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",           "isVisible":false},
  {"key":"serviceId",    "isVisible":false},
  {"key":"serviceName",  "isVisible":false},
  {"key":"resourceId",   "isVisible":false},
  {"key":"resourceName", "isVisible":true},
  {"key":"name",         "isVisible":true},
  {"key":"createdAt",    "isVisible":false},
  {"key":"creatorName",  "isVisible":false},
  {"key":"updatedAt",    "isVisible":false},
  {"key":"updaterName",  "isVisible":false},
  {"key":"archived",     "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",   "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'fields'), 'Archives', '[
  {"key":"core",         "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",           "isVisible":false},
  {"key":"serviceId",    "isVisible":false},
  {"key":"serviceName",  "isVisible":false},
  {"key":"resourceId",   "isVisible":false},
  {"key":"resourceName", "isVisible":true},
  {"key":"name",         "isVisible":true},
  {"key":"createdAt",    "isVisible":false},
  {"key":"creatorName",  "isVisible":false},
  {"key":"updatedAt",    "isVisible":false},
  {"key":"updaterName",  "isVisible":false},
  {"key":"archived",     "isVisible":true, "defaultWidth":"60px"},
  {"key":"archivedAt",   "isVisible":true}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'fields'), 'Audit', '[
  {"key":"core",         "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",           "isVisible":false},
  {"key":"serviceId",    "isVisible":false},
  {"key":"serviceName",  "isVisible":false},
  {"key":"resourceId",   "isVisible":false},
  {"key":"resourceName", "isVisible":true},
  {"key":"name",         "isVisible":true},
  {"key":"createdAt",    "isVisible":true},
  {"key":"creatorName",  "isVisible":true},
  {"key":"updatedAt",    "isVisible":true},
  {"key":"updaterName",  "isVisible":true},
  {"key":"archived",     "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",   "isVisible":false}
]', -1, 'system'),

-- scopes
((SELECT id FROM resource WHERE name = 'scopes'), 'Default', '[
  {"key":"id",          "isVisible":false},
  {"key":"core",        "isVisible":true,  "defaultWidth":"60px"},
  {"key":"routeId",     "isVisible":false},
  {"key":"routeName",   "isVisible":true},
  {"key":"resourceId",  "isVisible":false},
  {"key":"resourceName","isVisible":true},
  {"key":"name",        "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'scopes'), 'Compact', '[
  {"key":"id",          "isVisible":false},
  {"key":"core",        "isVisible":false, "defaultWidth":"60px"},
  {"key":"routeId",     "isVisible":false},
  {"key":"routeName",   "isVisible":true},
  {"key":"resourceId",  "isVisible":false},
  {"key":"resourceName","isVisible":true},
  {"key":"name",        "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'scopes'), 'Archives', '[
  {"key":"id",          "isVisible":false},
  {"key":"core",        "isVisible":false, "defaultWidth":"60px"},
  {"key":"routeId",     "isVisible":false},
  {"key":"routeName",   "isVisible":true},
  {"key":"resourceId",  "isVisible":false},
  {"key":"resourceName","isVisible":true},
  {"key":"name",        "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":true, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":true}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'scopes'), 'Audit', '[
  {"key":"id",          "isVisible":false},
  {"key":"core",        "isVisible":false, "defaultWidth":"60px"},
  {"key":"routeId",     "isVisible":false},
  {"key":"routeName",   "isVisible":true},
  {"key":"resourceId",  "isVisible":false},
  {"key":"resourceName","isVisible":true},
  {"key":"name",        "isVisible":true},
  {"key":"createdAt",   "isVisible":true},
  {"key":"creatorName", "isVisible":true},
  {"key":"updatedAt",   "isVisible":true},
  {"key":"updaterName", "isVisible":true},
  {"key":"archived",    "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":false}
]', -1, 'system'),

-- roles
((SELECT id FROM resource WHERE name = 'roles'), 'Default', '[
  {"key":"id",          "isVisible":false},
  {"key":"appId",       "isVisible":false},
  {"key":"appName",     "isVisible":true},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":true},
  {"key":"color",       "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'roles'), 'Compact', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":true},
  {"key":"color",       "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'roles'), 'Archives', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":true},
  {"key":"color",       "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":true, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":true}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'roles'), 'Audit', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":false},
  {"key":"color",       "isVisible":false},
  {"key":"createdAt",   "isVisible":true},
  {"key":"creatorName", "isVisible":true},
  {"key":"updatedAt",   "isVisible":true},
  {"key":"updaterName", "isVisible":true},
  {"key":"archived",    "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":false}
]', -1, 'system'),

-- conditions
((SELECT id FROM resource WHERE name = 'conditions'), 'Default', '[
  {"key":"id",         "isVisible":false},
  {"key":"name",       "isVisible":true},
  {"key":"fieldId",    "isVisible":false},
  {"key":"fieldName",  "isVisible":true},
  {"key":"op",         "isVisible":true,  "defaultWidth":"80px"},
  {"key":"value",      "isVisible":true},
  {"key":"color",      "isVisible":true},
  {"key":"createdAt",  "isVisible":false},
  {"key":"creatorName","isVisible":false},
  {"key":"updatedAt",  "isVisible":false},
  {"key":"updaterName","isVisible":false},
  {"key":"archived",   "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt", "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'conditions'), 'Compact', '[
  {"key":"id",         "isVisible":false},
  {"key":"name",       "isVisible":true},
  {"key":"fieldId",    "isVisible":false},
  {"key":"fieldName",  "isVisible":true},
  {"key":"op",         "isVisible":true,  "defaultWidth":"80px"},
  {"key":"value",      "isVisible":true},
  {"key":"color",      "isVisible":false},
  {"key":"createdAt",  "isVisible":false},
  {"key":"creatorName","isVisible":false},
  {"key":"updatedAt",  "isVisible":false},
  {"key":"updaterName","isVisible":false},
  {"key":"archived",   "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt", "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'conditions'), 'Archives', '[
  {"key":"id",         "isVisible":false},
  {"key":"name",       "isVisible":true},
  {"key":"fieldId",    "isVisible":false},
  {"key":"fieldName",  "isVisible":true},
  {"key":"op",         "isVisible":true,  "defaultWidth":"80px"},
  {"key":"value",      "isVisible":true},
  {"key":"color",      "isVisible":false},
  {"key":"createdAt",  "isVisible":false},
  {"key":"creatorName","isVisible":false},
  {"key":"updatedAt",  "isVisible":false},
  {"key":"updaterName","isVisible":false},
  {"key":"archived",   "isVisible":true, "defaultWidth":"60px"},
  {"key":"archivedAt", "isVisible":true}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'conditions'), 'Audit', '[
  {"key":"id",         "isVisible":false},
  {"key":"name",       "isVisible":true},
  {"key":"fieldId",    "isVisible":false},
  {"key":"fieldName",  "isVisible":true},
  {"key":"op",         "isVisible":false},
  {"key":"value",      "isVisible":false},
  {"key":"color",      "isVisible":false},
  {"key":"createdAt",  "isVisible":true},
  {"key":"creatorName","isVisible":true},
  {"key":"updatedAt",  "isVisible":true},
  {"key":"updaterName","isVisible":true},
  {"key":"archived",   "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt", "isVisible":false}
]', -1, 'system'),

-- applications
((SELECT id FROM resource WHERE name = 'applications'), 'Default', '[
  {"key":"core",        "isVisible":true,  "defaultWidth":"60px"},
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'applications'), 'Compact', '[
  {"key":"core",        "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":false},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'applications'), 'Archives', '[
  {"key":"core",        "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":false},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":true, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":true}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'applications'), 'Audit', '[
  {"key":"core",        "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":false},
  {"key":"createdAt",   "isVisible":true},
  {"key":"creatorName", "isVisible":true},
  {"key":"updatedAt",   "isVisible":true},
  {"key":"updaterName", "isVisible":true},
  {"key":"archived",    "isVisible":false, "defaultWidth":"60px"},
  {"key":"archivedAt",  "isVisible":false}
]', -1, 'system'),

-- permissions
((SELECT id FROM resource WHERE name = 'permissions'), 'Default', '[
  {"key":"id",            "isVisible":false},
  {"key":"serviceId",     "isVisible":false},
  {"key":"serviceName",   "isVisible":true},
  {"key":"resourceId",    "isVisible":false},
  {"key":"resourceName",  "isVisible":true},
  {"key":"routeId",       "isVisible":false},
  {"key":"routeName",     "isVisible":true},
  {"key":"operationId",   "isVisible":false},
  {"key":"operationName", "isVisible":true},
  {"key":"fields",        "isVisible":true},
  {"key":"scopes",        "isVisible":true},
  {"key":"conditionId",   "isVisible":false},
  {"key":"conditionName", "isVisible":true}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'permissions'), 'Compact', '[
  {"key":"id",            "isVisible":false},
  {"key":"serviceId",     "isVisible":false},
  {"key":"serviceName",   "isVisible":false},
  {"key":"resourceId",    "isVisible":false},
  {"key":"resourceName",  "isVisible":true},
  {"key":"routeId",       "isVisible":false},
  {"key":"routeName",     "isVisible":true},
  {"key":"operationId",   "isVisible":false},
  {"key":"operationName", "isVisible":true},
  {"key":"fields",        "isVisible":false},
  {"key":"scopes",        "isVisible":false},
  {"key":"conditionId",   "isVisible":false},
  {"key":"conditionName", "isVisible":false}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'permissions'), 'Fields', '[
  {"key":"id",            "isVisible":false},
  {"key":"serviceId",     "isVisible":false},
  {"key":"serviceName",   "isVisible":false},
  {"key":"resourceId",    "isVisible":false},
  {"key":"resourceName",  "isVisible":true},
  {"key":"routeId",       "isVisible":false},
  {"key":"routeName",     "isVisible":true},
  {"key":"operationId",   "isVisible":false},
  {"key":"operationName", "isVisible":true},
  {"key":"fields",        "isVisible":true},
  {"key":"scopes",        "isVisible":true},
  {"key":"conditionId",   "isVisible":false},
  {"key":"conditionName", "isVisible":true}
]', -1, 'system'),
((SELECT id FROM resource WHERE name = 'permissions'), 'Full', '[
  {"key":"id",            "isVisible":true},
  {"key":"serviceId",     "isVisible":false},
  {"key":"serviceName",   "isVisible":true},
  {"key":"resourceId",    "isVisible":false},
  {"key":"resourceName",  "isVisible":true},
  {"key":"routeId",       "isVisible":false},
  {"key":"routeName",     "isVisible":true},
  {"key":"operationId",   "isVisible":false},
  {"key":"operationName", "isVisible":true},
  {"key":"fields",        "isVisible":true},
  {"key":"scopes",        "isVisible":true},
  {"key":"conditionId",   "isVisible":false},
  {"key":"conditionName", "isVisible":true}
]', -1, 'system')

;

ANALYZE;
