ARG NODE_VERSION=24.11.0-alpine3.22

FROM node:${NODE_VERSION} AS deps
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --ignore-scripts --no-fund --no-audit --loglevel=error

FROM node:${NODE_VERSION} AS runtime

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

RUN apk add --no-cache tzdata

ARG TZ=UTC
ENV TZ=${TZ}

ARG UID=1000
ARG GID=1000
RUN addgroup -S appgroup -g ${GID} \
  && adduser -S -G appgroup -u ${UID} appuser

WORKDIR /usr/src/app
COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY --chown=appuser:appgroup package*.json ./
COPY --chown=appuser:appgroup . .

USER appuser

CMD ["npm", "run", "dev"]
