ARG NODE_VERSION=24.11.0-alpine3.22

# Stage 1: install production dependencies
FROM node:${NODE_VERSION} AS deps
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --only=production --loglevel=error --ignore-scripts --no-fund

# Stage 2: final image
FROM node:${NODE_VERSION}

ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}

ARG TZ
ENV TZ=${TZ}

# Create a new simple user
ARG UID
ARG GID
RUN deluser --remove-home node \
  && addgroup -S usergroup -g ${GID} \
  && adduser -G usergroup -S user -u ${UID}
USER user

WORKDIR /usr/src/app
COPY --chown=user:usergroup --from=deps /usr/src/app/node_modules ./node_modules
COPY --chown=user:usergroup ./src ./src

CMD [ "node", "--run", "start" ]