import { ExcelExportMode, FilterLevel } from "@dwtechs/crud-builder";
import { AdminEntity } from "./app.entities";

type TableInfo = {
  label: string;
  title: string;
  entityId: AdminEntity;
  editionDialogSize: "xs" | "s" | "m" | "l";
  filterLevel: FilterLevel;
  isPreferencesModeEnabled: boolean;
  isExcelExportEnabled: boolean;
  excelExportMode: ExcelExportMode;
  additionalReadonlyProperties: Record<string, boolean>;
};

export const TABLES: Record<AdminEntity, TableInfo> = {
  routes: {
    label: $localize`:@@TableLabels_Route:Route`,
    title: $localize`:@@TableLabels_Routes:Routes`,
    entityId: "routes",
    editionDialogSize: "m",
    filterLevel: "advanced",
    isPreferencesModeEnabled: true,
    isExcelExportEnabled: true,
    excelExportMode: "local",
    additionalReadonlyProperties: { core: true },
  },
  consumers: {
    label: $localize`:@@TableLabels_Consumer:Consumer`,
    title: $localize`:@@TableLabels_Consumers:Consumers`,
    entityId: "consumers",
    editionDialogSize: "s",
    filterLevel: "advanced",
    isPreferencesModeEnabled: true,
    isExcelExportEnabled: true,
    excelExportMode: "local",
    additionalReadonlyProperties: { core: true },
  },
  services: {
    label: $localize`:@@TableLabels_Service:Service`,
    title: $localize`:@@TableLabels_Services:Services`,
    entityId: "services",
    editionDialogSize: "s",
    filterLevel: "advanced",
    isPreferencesModeEnabled: true,
    isExcelExportEnabled: true,
    excelExportMode: "local",
    additionalReadonlyProperties: { core: true },
  },
  resources: {
    label: $localize`:@@TableLabels_Resource:Resource`,
    title: $localize`:@@TableLabels_Resources:Resources`,
    entityId: "resources",
    editionDialogSize: "s",
    filterLevel: "advanced",
    isPreferencesModeEnabled: true,
    isExcelExportEnabled: true,
    excelExportMode: "local",
    additionalReadonlyProperties: { core: true },
  },
  cors: {
    label: $localize`:@@TableLabels_Cors:CORS`,
    title: $localize`:@@TableLabels_CorsPlural:CORS`,
    entityId: "cors",
    editionDialogSize: "s",
    filterLevel: "advanced",
    isPreferencesModeEnabled: true,
    isExcelExportEnabled: true,
    excelExportMode: "local",
    additionalReadonlyProperties: { core: true },
  },
  operations: {
    label: $localize`:@@TableLabels_Operation:Opération`,
    title: $localize`:@@TableLabels_Operations:Opérations`,
    entityId: "operations",
    editionDialogSize: "s",
    filterLevel: "advanced",
    isPreferencesModeEnabled: true,
    isExcelExportEnabled: true,
    excelExportMode: "local",
    additionalReadonlyProperties: { core: true },
  },
  methods: {
    label: $localize`:@@TableLabels_Method:Method`,
    title: $localize`:@@TableLabels_Methods:Methods`,
    entityId: "methods",
    editionDialogSize: "s",
    filterLevel: "advanced",
    isPreferencesModeEnabled: true,
    isExcelExportEnabled: true,
    excelExportMode: "local",
    additionalReadonlyProperties: { core: true },
  },
  fields: {
    label: $localize`:@@TableLabels_Field:Field`,
    title: $localize`:@@TableLabels_Fields:Fields`,
    entityId: "fields",
    editionDialogSize: "s",
    filterLevel: "advanced",
    isPreferencesModeEnabled: true,
    isExcelExportEnabled: true,
    excelExportMode: "local",
    additionalReadonlyProperties: { core: true },
  },
  scopes: {
    label: $localize`:@@TableLabels_Scope:Scope`,
    title: $localize`:@@TableLabels_Scopes:Scopes`,
    entityId: "scopes",
    editionDialogSize: "s",
    filterLevel: "advanced",
    isPreferencesModeEnabled: true,
    isExcelExportEnabled: true,
    excelExportMode: "local",
    additionalReadonlyProperties: { core: true },
  },
  roles: {
    label: $localize`:@@TableLabels_Role:Role`,
    title: $localize`:@@TableLabels_Roles:Roles`,
    entityId: "roles",
    editionDialogSize: "s",
    filterLevel: "advanced",
    isPreferencesModeEnabled: true,
    isExcelExportEnabled: true,
    excelExportMode: "local",
    additionalReadonlyProperties: { core: true },
  },
  permissions: {
    label: $localize`:@@TableLabels_Permission:Permission`,
    title: $localize`:@@TableLabels_Permissions:Permissions`,
    entityId: "permissions",
    editionDialogSize: "s",
    filterLevel: "advanced",
    isPreferencesModeEnabled: true,
    isExcelExportEnabled: true,
    excelExportMode: "local",
    additionalReadonlyProperties: { core: true },
  },
  applications: {
    label: $localize`:@@TableLabels_Application:Application`,
    title: $localize`:@@TableLabels_Applications:Applications`,
    entityId: "applications",
    editionDialogSize: "s",
    filterLevel: "advanced",
    isPreferencesModeEnabled: true,
    isExcelExportEnabled: true,
    excelExportMode: "local",
    additionalReadonlyProperties: { core: true },
  },
  conditions: {
    label: $localize`:@@TableLabels_Condition:Condition`,
    title: $localize`:@@TableLabels_Conditions:Conditions`,
    entityId: "conditions",
    editionDialogSize: "s",
    filterLevel: "advanced",
    isPreferencesModeEnabled: true,
    isExcelExportEnabled: true,
    excelExportMode: "local",
    additionalReadonlyProperties: { core: true },
  },
} as const;
