ARG NODE_VERSION
FROM node:${NODE_VERSION}

LABEL org.opencontainers.image.description="Gatelin OpenAPI/Swagger UI (development)"

ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}

# change apk repos
# RUN rm /etc/apk/repositories
# RUN --mount=type=secret,id=apk_repository,target=/etc/apk/repositories,required=true 
RUN apk update && apk add tzdata 

ARG TZ
ENV TZ=${TZ}

# Create a new simple user 
ARG UID
ARG GID
RUN deluser --remove-home node && addgroup -S usergroup -g ${GID} && adduser -G usergroup -S user -u ${UID}
USER user

WORKDIR /usr/src/app
COPY --chown=user:usergroup --chmod=640 package*.json ./

RUN npm i --loglevel=error --ignore-scripts --no-fund


CMD [ "npm", "run", "dev" ]