INSERT INTO preference ("userId", resource, name, conf, "isActive", locked, "creatorId", "creatorName") VALUES

-- routes
(-1, 'routes', 'Default', '[
  {"key":"core",          "isVisible":true,  "defaultWidth":"60px"},
  {"key":"protected",     "isVisible":true,  "defaultWidth":"60px"},
  {"key":"id",            "isVisible":false},
  {"key":"serviceId",     "isVisible":false},
  {"key":"serviceName",   "isVisible":true},
  {"key":"resourceId",    "isVisible":false},
  {"key":"resourceName",  "isVisible":true},
  {"key":"name",          "isVisible":true},
  {"key":"description",   "isVisible":true},
  {"key":"pattern",       "isVisible":true},
  {"key":"operationId",   "isVisible":false},
  {"key":"operationName", "isVisible":true},
  {"key":"methodIds",     "isVisible":false},
  {"key":"methodNames",   "isVisible":true},
  {"key":"createdAt",     "isVisible":false},
  {"key":"creatorName",   "isVisible":false},
  {"key":"updatedAt",     "isVisible":false},
  {"key":"updaterName",   "isVisible":false},
  {"key":"archived",      "isVisible":false},
  {"key":"archivedAt",    "isVisible":false}
]', true, true, -1, 'system'),
(-1, 'routes', 'Compact', '[
  {"key":"core",          "isVisible":false, "defaultWidth":"60px"},
  {"key":"protected",     "isVisible":true,  "defaultWidth":"60px"},
  {"key":"id",            "isVisible":false},
  {"key":"serviceId",     "isVisible":false},
  {"key":"serviceName",   "isVisible":true},
  {"key":"resourceId",    "isVisible":false},
  {"key":"resourceName",  "isVisible":true},
  {"key":"name",          "isVisible":true},
  {"key":"description",   "isVisible":false},
  {"key":"pattern",       "isVisible":true},
  {"key":"operationId",   "isVisible":false},
  {"key":"operationName", "isVisible":true},
  {"key":"methodIds",     "isVisible":false},
  {"key":"methodNames",   "isVisible":true},
  {"key":"createdAt",     "isVisible":false},
  {"key":"creatorName",   "isVisible":false},
  {"key":"updatedAt",     "isVisible":false},
  {"key":"updaterName",   "isVisible":false},
  {"key":"archived",      "isVisible":false},
  {"key":"archivedAt",    "isVisible":false}
]', false, true, -1, 'system'),
(-1, 'routes', 'Archives', '[
  {"key":"core",          "isVisible":false, "defaultWidth":"60px"},
  {"key":"protected",     "isVisible":true,  "defaultWidth":"60px"},
  {"key":"id",            "isVisible":false},
  {"key":"serviceId",     "isVisible":false},
  {"key":"serviceName",   "isVisible":true},
  {"key":"resourceId",    "isVisible":false},
  {"key":"resourceName",  "isVisible":true},
  {"key":"name",          "isVisible":true},
  {"key":"description",   "isVisible":false},
  {"key":"pattern",       "isVisible":true},
  {"key":"operationId",   "isVisible":false},
  {"key":"operationName", "isVisible":true},
  {"key":"methodIds",     "isVisible":false},
  {"key":"methodNames",   "isVisible":true},
  {"key":"createdAt",     "isVisible":false},
  {"key":"creatorName",   "isVisible":false},
  {"key":"updatedAt",     "isVisible":false},
  {"key":"updaterName",   "isVisible":false},
  {"key":"archived",      "isVisible":true},
  {"key":"archivedAt",    "isVisible":true}
]', false, true, -1, 'system'),
(-1, 'routes', 'Audit', '[
  {"key":"core",          "isVisible":false, "defaultWidth":"60px"},
  {"key":"protected",     "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",            "isVisible":false},
  {"key":"serviceId",     "isVisible":false},
  {"key":"serviceName",   "isVisible":true},
  {"key":"resourceId",    "isVisible":false},
  {"key":"resourceName",  "isVisible":true},
  {"key":"name",          "isVisible":true},
  {"key":"description",   "isVisible":false},
  {"key":"pattern",       "isVisible":false},
  {"key":"operationId",   "isVisible":false},
  {"key":"operationName", "isVisible":false},
  {"key":"methodIds",     "isVisible":false},
  {"key":"methodNames",   "isVisible":false},
  {"key":"createdAt",     "isVisible":true},
  {"key":"creatorName",   "isVisible":true},
  {"key":"updatedAt",     "isVisible":true},
  {"key":"updaterName",   "isVisible":true},
  {"key":"archived",      "isVisible":false},
  {"key":"archivedAt",    "isVisible":false}
]', false, true, -1, 'system'),

-- consumers
(-1, 'consumers', 'Default', '[
  {"key":"id",           "isVisible":false},
  {"key":"userId",       "isVisible":true,  "defaultWidth":"80px"},
  {"key":"nickname",     "isVisible":true,  "defaultWidth":"100px"},
  {"key":"accessToken",  "isVisible":true, "defaultWidth":"300px"},
  {"key":"refreshToken", "isVisible":true, "defaultWidth":"300px"},
  {"key":"roles",        "isVisible":true},
  {"key":"createdAt",    "isVisible":false},
  {"key":"creatorName",  "isVisible":false},
  {"key":"updatedAt",    "isVisible":false},
  {"key":"updaterName",  "isVisible":false},
  {"key":"archived",     "isVisible":true},
  {"key":"archivedAt",   "isVisible":false}
]', true, true, -1, 'system'),
(-1, 'consumers', 'Compact', '[
  {"key":"id",           "isVisible":false},
  {"key":"userId",       "isVisible":true,  "defaultWidth":"80px"},
  {"key":"nickname",     "isVisible":true,  "defaultWidth":"100px"},
  {"key":"accessToken",  "isVisible":false, "defaultWidth":"300px"},
  {"key":"refreshToken", "isVisible":false, "defaultWidth":"300px"},
  {"key":"roles",        "isVisible":true},
  {"key":"createdAt",    "isVisible":false},
  {"key":"creatorName",  "isVisible":false},
  {"key":"updatedAt",    "isVisible":false},
  {"key":"updaterName",  "isVisible":false},
  {"key":"archived",     "isVisible":false},
  {"key":"archivedAt",   "isVisible":false}
]', false, true, -1, 'system'),
(-1, 'consumers', 'Archives', '[
  {"key":"id",           "isVisible":false},
  {"key":"userId",       "isVisible":true,  "defaultWidth":"80px"},
  {"key":"nickname",     "isVisible":true,  "defaultWidth":"100px"},
  {"key":"accessToken",  "isVisible":false, "defaultWidth":"300px"},
  {"key":"refreshToken", "isVisible":false, "defaultWidth":"300px"},
  {"key":"roles",        "isVisible":true},
  {"key":"createdAt",    "isVisible":false},
  {"key":"creatorName",  "isVisible":false},
  {"key":"updatedAt",    "isVisible":false},
  {"key":"updaterName",  "isVisible":false},
  {"key":"archived",     "isVisible":true},
  {"key":"archivedAt",   "isVisible":true}
]', false, true, -1, 'system'),

-- services
(-1, 'services', 'Default', '[
  {"key":"core",       "isVisible":true,  "defaultWidth":"60px"},
  {"key":"id",         "isVisible":false},
  {"key":"appId",      "isVisible":false},
  {"key":"appName",    "isVisible":true},
  {"key":"name",       "isVisible":true},
  {"key":"pattern",    "isVisible":true},
  {"key":"createdAt",  "isVisible":false},
  {"key":"creatorName","isVisible":false},
  {"key":"updatedAt",  "isVisible":false},
  {"key":"updaterName","isVisible":false},
  {"key":"archived",   "isVisible":false},
  {"key":"archivedAt", "isVisible":false}
]', true, true, -1, 'system'),
(-1, 'services', 'Compact', '[
  {"key":"core",       "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",         "isVisible":false},
  {"key":"name",       "isVisible":true},
  {"key":"pattern",    "isVisible":true},
  {"key":"createdAt",  "isVisible":false},
  {"key":"creatorName","isVisible":false},
  {"key":"updatedAt",  "isVisible":false},
  {"key":"updaterName","isVisible":false},
  {"key":"archived",   "isVisible":false},
  {"key":"archivedAt", "isVisible":false}
]', false, true, -1, 'system'),
(-1, 'services', 'Archives', '[
  {"key":"core",       "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",         "isVisible":false},
  {"key":"name",       "isVisible":true},
  {"key":"pattern",    "isVisible":true},
  {"key":"createdAt",  "isVisible":false},
  {"key":"creatorName","isVisible":false},
  {"key":"updatedAt",  "isVisible":false},
  {"key":"updaterName","isVisible":false},
  {"key":"archived",   "isVisible":true},
  {"key":"archivedAt", "isVisible":true}
]', false, true, -1, 'system'),
(-1, 'services', 'Audit', '[
  {"key":"core",       "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",         "isVisible":false},
  {"key":"name",       "isVisible":true},
  {"key":"pattern",    "isVisible":false},
  {"key":"createdAt",  "isVisible":true},
  {"key":"creatorName","isVisible":true},
  {"key":"updatedAt",  "isVisible":true},
  {"key":"updaterName","isVisible":true},
  {"key":"archived",   "isVisible":false},
  {"key":"archivedAt", "isVisible":false}
]', false, true, -1, 'system'),

-- resources
(-1, 'resources', 'Default', '[
  {"key":"core",        "isVisible":true,  "defaultWidth":"60px"},
  {"key":"id",          "isVisible":false},
  {"key":"serviceId",   "isVisible":false},
  {"key":"serviceName", "isVisible":true},
  {"key":"name",        "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false},
  {"key":"archivedAt",  "isVisible":false}
]', true, true, -1, 'system'),
(-1, 'resources', 'Compact', '[
  {"key":"core",        "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",          "isVisible":false},
  {"key":"serviceId",   "isVisible":false},
  {"key":"serviceName", "isVisible":true},
  {"key":"name",        "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false},
  {"key":"archivedAt",  "isVisible":false}
]', false, true, -1, 'system'),
(-1, 'resources', 'Archives', '[
  {"key":"core",        "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",          "isVisible":false},
  {"key":"serviceId",   "isVisible":false},
  {"key":"serviceName", "isVisible":true},
  {"key":"name",        "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":true},
  {"key":"archivedAt",  "isVisible":true}
]', false, true, -1, 'system'),
(-1, 'resources', 'Audit', '[
  {"key":"core",        "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",          "isVisible":false},
  {"key":"serviceId",   "isVisible":false},
  {"key":"serviceName", "isVisible":true},
  {"key":"name",        "isVisible":true},
  {"key":"createdAt",   "isVisible":true},
  {"key":"creatorName", "isVisible":true},
  {"key":"updatedAt",   "isVisible":true},
  {"key":"updaterName", "isVisible":true},
  {"key":"archived",    "isVisible":false},
  {"key":"archivedAt",  "isVisible":false}
]', false, true, -1, 'system'),

-- cors
(-1, 'cors', 'Default', '[
  {"key":"id",         "isVisible":false},
  {"key":"name",       "isVisible":true},
  {"key":"createdAt",  "isVisible":false},
  {"key":"creatorName","isVisible":false},
  {"key":"updatedAt",  "isVisible":false},
  {"key":"updaterName","isVisible":false},
  {"key":"archived",   "isVisible":false},
  {"key":"archivedAt", "isVisible":false}
]', true, true, -1, 'system'),
(-1, 'cors', 'Compact', '[
  {"key":"id",         "isVisible":false},
  {"key":"name",       "isVisible":true},
  {"key":"createdAt",  "isVisible":false},
  {"key":"creatorName","isVisible":false},
  {"key":"updatedAt",  "isVisible":false},
  {"key":"updaterName","isVisible":false},
  {"key":"archived",   "isVisible":false},
  {"key":"archivedAt", "isVisible":false}
]', false, true, -1, 'system'),
(-1, 'cors', 'Archives', '[
  {"key":"id",         "isVisible":false},
  {"key":"name",       "isVisible":true},
  {"key":"createdAt",  "isVisible":false},
  {"key":"creatorName","isVisible":false},
  {"key":"updatedAt",  "isVisible":false},
  {"key":"updaterName","isVisible":false},
  {"key":"archived",   "isVisible":true},
  {"key":"archivedAt", "isVisible":true}
]', false, true, -1, 'system'),
(-1, 'cors', 'Audit', '[
  {"key":"id",         "isVisible":false},
  {"key":"name",       "isVisible":true},
  {"key":"createdAt",  "isVisible":true},
  {"key":"creatorName","isVisible":true},
  {"key":"updatedAt",  "isVisible":true},
  {"key":"updaterName","isVisible":true},
  {"key":"archived",   "isVisible":false},
  {"key":"archivedAt", "isVisible":false}
]', false, true, -1, 'system'),

-- operations
(-1, 'operations', 'Default', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":true},
  {"key":"color",       "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false},
  {"key":"archivedAt",  "isVisible":false}
]', true, true, -1, 'system'),
(-1, 'operations', 'Compact', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false},
  {"key":"archivedAt",  "isVisible":false}
]', false, true, -1, 'system'),
(-1, 'operations', 'Archives', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":true},
  {"key":"archivedAt",  "isVisible":true}
]', false, true, -1, 'system'),
(-1, 'operations', 'Audit', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":false},
  {"key":"createdAt",   "isVisible":true},
  {"key":"creatorName", "isVisible":true},
  {"key":"updatedAt",   "isVisible":true},
  {"key":"updaterName", "isVisible":true},
  {"key":"archived",    "isVisible":false},
  {"key":"archivedAt",  "isVisible":false}
]', false, true, -1, 'system'),

-- fields
(-1, 'fields', 'Default', '[
  {"key":"locked",       "isVisible":true,  "defaultWidth":"60px"},
  {"key":"id",           "isVisible":false},
  {"key":"resourceId",   "isVisible":false},
  {"key":"resourceName", "isVisible":true},
  {"key":"serviceName",  "isVisible":true},
  {"key":"name",         "isVisible":true},
  {"key":"createdAt",    "isVisible":false},
  {"key":"creatorName",  "isVisible":false},
  {"key":"updatedAt",    "isVisible":false},
  {"key":"updaterName",  "isVisible":false},
  {"key":"archived",     "isVisible":false},
  {"key":"archivedAt",   "isVisible":false}
]', true, true, -1, 'system'),
(-1, 'fields', 'Compact', '[
  {"key":"locked",       "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",           "isVisible":false},
  {"key":"resourceId",   "isVisible":false},
  {"key":"resourceName", "isVisible":true},
  {"key":"name",         "isVisible":true},
  {"key":"createdAt",    "isVisible":false},
  {"key":"creatorName",  "isVisible":false},
  {"key":"updatedAt",    "isVisible":false},
  {"key":"updaterName",  "isVisible":false},
  {"key":"archived",     "isVisible":false},
  {"key":"archivedAt",   "isVisible":false}
]', false, true, -1, 'system'),
(-1, 'fields', 'Archives', '[
  {"key":"locked",       "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",           "isVisible":false},
  {"key":"resourceId",   "isVisible":false},
  {"key":"resourceName", "isVisible":true},
  {"key":"name",         "isVisible":true},
  {"key":"createdAt",    "isVisible":false},
  {"key":"creatorName",  "isVisible":false},
  {"key":"updatedAt",    "isVisible":false},
  {"key":"updaterName",  "isVisible":false},
  {"key":"archived",     "isVisible":true},
  {"key":"archivedAt",   "isVisible":true}
]', false, true, -1, 'system'),
(-1, 'fields', 'Audit', '[
  {"key":"locked",       "isVisible":false, "defaultWidth":"60px"},
  {"key":"id",           "isVisible":false},
  {"key":"resourceId",   "isVisible":false},
  {"key":"resourceName", "isVisible":true},
  {"key":"name",         "isVisible":true},
  {"key":"createdAt",    "isVisible":true},
  {"key":"creatorName",  "isVisible":true},
  {"key":"updatedAt",    "isVisible":true},
  {"key":"updaterName",  "isVisible":true},
  {"key":"archived",     "isVisible":false},
  {"key":"archivedAt",   "isVisible":false}
]', false, true, -1, 'system'),

-- scopes
(-1, 'scopes', 'Default', '[
  {"key":"id",          "isVisible":false},
  {"key":"routeId",     "isVisible":false},
  {"key":"routeName",   "isVisible":true},
  {"key":"resourceName","isVisible":true},
  {"key":"name",        "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false},
  {"key":"archivedAt",  "isVisible":false}
]', true, true, -1, 'system'),
(-1, 'scopes', 'Compact', '[
  {"key":"id",          "isVisible":false},
  {"key":"routeId",     "isVisible":false},
  {"key":"routeName",   "isVisible":true},
  {"key":"name",        "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false},
  {"key":"archivedAt",  "isVisible":false}
]', false, true, -1, 'system'),
(-1, 'scopes', 'Archives', '[
  {"key":"id",          "isVisible":false},
  {"key":"routeId",     "isVisible":false},
  {"key":"routeName",   "isVisible":true},
  {"key":"name",        "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":true},
  {"key":"archivedAt",  "isVisible":true}
]', false, true, -1, 'system'),
(-1, 'scopes', 'Audit', '[
  {"key":"id",          "isVisible":false},
  {"key":"routeId",     "isVisible":false},
  {"key":"routeName",   "isVisible":true},
  {"key":"name",        "isVisible":true},
  {"key":"createdAt",   "isVisible":true},
  {"key":"creatorName", "isVisible":true},
  {"key":"updatedAt",   "isVisible":true},
  {"key":"updaterName", "isVisible":true},
  {"key":"archived",    "isVisible":false},
  {"key":"archivedAt",  "isVisible":false}
]', false, true, -1, 'system'),

-- roles
(-1, 'roles', 'Default', '[
  {"key":"id",          "isVisible":false},
  {"key":"appId",       "isVisible":false},
  {"key":"appName",     "isVisible":true},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":true},
  {"key":"color",       "isVisible":true},
  {"key":"active",      "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false},
  {"key":"archivedAt",  "isVisible":false}
]', true, true, -1, 'system'),
(-1, 'roles', 'Compact', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":true},
  {"key":"color",       "isVisible":true},
  {"key":"active",      "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":false},
  {"key":"archivedAt",  "isVisible":false}
]', false, true, -1, 'system'),
(-1, 'roles', 'Archives', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":true},
  {"key":"color",       "isVisible":true},
  {"key":"active",      "isVisible":true},
  {"key":"createdAt",   "isVisible":false},
  {"key":"creatorName", "isVisible":false},
  {"key":"updatedAt",   "isVisible":false},
  {"key":"updaterName", "isVisible":false},
  {"key":"archived",    "isVisible":true},
  {"key":"archivedAt",  "isVisible":true}
]', false, true, -1, 'system'),
(-1, 'roles', 'Audit', '[
  {"key":"id",          "isVisible":false},
  {"key":"name",        "isVisible":true},
  {"key":"description", "isVisible":false},
  {"key":"color",       "isVisible":false},
  {"key":"active",      "isVisible":false},
  {"key":"createdAt",   "isVisible":true},
  {"key":"creatorName", "isVisible":true},
  {"key":"updatedAt",   "isVisible":true},
  {"key":"updaterName", "isVisible":true},
  {"key":"archived",    "isVisible":false},
  {"key":"archivedAt",  "isVisible":false}
]', false, true, -1, 'system')

;

ANALYZE;
