// @ts-check
import { log } from "@dwtechs/winstan";
import csmerSvc from "../../services/consumer.js";


/**
 * @typedef {object} Consumer
 * @property {number} id - The unique identifier of the consumer
 * @property {number} userId - The user ID from ms_user service
 * @property {string} accessToken - The consumer's access token
 * @property {string} refreshToken - The consumer's refresh token
 * @property {Array<string>} roles - Array of roles assigned to the consumer
 */

/**
 * @typedef {object} ExtendedRequest
 * @property {object} body - Request body containing tokens
 * @property {string} body.accessToken - The access token to validate
 * @property {string} body.refreshToken - The refresh token to validate
 * @property {object} decodedRefreshToken - Previously decoded refresh token
 * @property {string} decodedRefreshToken.iss - The issuer (consumer ID) from decoded token
 * @property {Consumer} consumer - Consumer object added by this middleware
 */

/**
 * Express middleware that validates JWT tokens by matching access and refresh tokens
 * against stored consumer data. Checks cache first, then database if needed.
 * This middleware ensures that the tokens provided match the tokens stored in the
 * consumer cache/database, preventing token replay attacks and ensuring token authenticity.
 *
 * @param {import('express').Request} req - Express request object containing accessToken and refreshToken in body
 * @param {import('express').Response} res - Express response object for sending HTTP responses
 * @param {import('express').NextFunction} next - Express next function to pass control to the next middleware
 * @return {void} Calls next() on success or next(error) on validation failure
 * @throws {object} Returns 404 error if consumer not found, or 401 error if tokens don't match
 * @example
 * // Use as Express middleware after JWT decoding
 * import { checkToken } from './middlewares/validators/check-token.js';
 * app.post('/refresh', decodeRefreshToken, checkToken, refreshTokens);
 * 
 * // After successful validation, req object will have:
 * // req.consumer - complete consumer object from cache
 */
export default async function getFromCache(req, res, next) {
  
  const at = res.locals.tokens.access;
  log.debug(`get Consumer with access token : accessToken=${at}`);
  const c = csmerSvc.getOne(at);
  
  if (!c)
    return next({
      status: 404,
      msg: "Consumer not found",
    });
  
  log.debug(`Consumer found: ${JSON.stringify(c)}`);
  res.locals.consumer = c;
  next();

}


/**
 * Adds newly created consumer to cache after successful database insertion.
 * This middleware runs after cEnt.add completes the INSERT operation.
 * The database auto-generates the consumer id and the library adds it back to the rows array.
 * 
 * @param {import('express').Request} req - Express request object
 * @param {import('express').Response} res - Express response object
 * @param {import('express').NextFunction} next - Express next function
 * 
 * @return {void} Calls next() after adding consumer to cache
 * 
 * @example
 * // Used in POST /consumers route after database insertion
 * const addConsumer = [ refreshTokens, cEnt.validateArray, cEnt.add, addToCache ];
 * 
 * // After cEnt.add, res.locals.rows[0] contains:
 * // { id: 16, userId: 123, nickname, accessToken, refreshToken, rolesArrayAgg }
 * // where id was auto-generated by the database and returned via RETURNING clause
 */
function addToCache(req, res, next) {
  const c = res.locals.rows[0]; // Newly created consumer from database
  log.debug(`Adding consumer to cache : ${JSON.stringify(c)}`);
  // Add consumer to cache
  csmerSvc.addToCache(c);
  next();
}

/**
 * Updates consumer tokens in cache after successful database update
 * Middleware in updateConsumer stack of PUT /consumers route
 * 
 * @param {Object} req - Express request
 * @param {Object} req.body - Request body
 * @param {Array} req.body.rows - Array with updated consumer data
 * 
 * @param {Object} res - Express response
 * @param {Object} res.locals - Response locals
 * 
 * @param {Function} next - Express next function
 * 
 * @modifies Updates in-memory consumer cache with new tokens
 * 
 * INPUT:
 *   req.body.rows[0] = { id, accessToken, refreshToken }
 * 
 * OUTPUT:
 *   Cache updated with new tokens for the consumer
 */
function updateCache(req, res, next) {
  const c = req.body.rows[0];
  log.debug(`Updating consumer ${c.id} in cache`);
  // Update consumer in cache
  const updatedC = csmerSvc.updateCache(c.id, c.accessToken, c.refreshToken);
  if (!updatedC)
    return next({
      status: 404,
      msg: "Consumer not updated in cache",
    });

  next();
}

function deleteFromCache(req, res, next) {
  const c = req.body.rows[0];
  log.debug(`Deleting consumer ${c.id} from cache`);
  csmerSvc.deleteFromCache(c.id);
  next();
}

export {
  getFromCache,
  addToCache,
  updateCache,
  deleteFromCache,
};