// @ts-check
import { log } from "@dwtechs/winstan";
import csmerSvc from "../../services/consumer.js";

/**
 * @typedef {object} Consumer
 * @property {number} id - The unique identifier of the consumer
 * @property {number} userId - The user ID from ms_user service
 * @property {string} accessToken - The consumer's access token
 * @property {string} refreshToken - The consumer's refresh token
 * @property {Array<string>} roles - Array of roles assigned to the consumer
 */

/**
 * Adds newly created consumer to cache after successful database insertion.
 * This middleware runs after cEnt.add completes the INSERT operation.
 * The database auto-generates the consumer id and the library adds it back to the rows array.
 *
 * @param {import('express').Request} req - Express request object
 * @param {import('express').Response} res - Express response object
 * @param {import('express').NextFunction} next - Express next function
 *
 * @return {void} Calls next() after adding consumer to cache
 *
 * @example
 * // Used in POST /consumers route after database insertion
 * const addConsumer = [ refreshTokens, cEnt.validateArray, cEnt.add, addToCache ];
 *
 * // After cEnt.add, res.locals.rows[0] contains:
 * // { id: 16, userId: 123, nickname, accessToken, refreshToken, roles }
 * // where id was auto-generated by the database and returned via RETURNING clause
 */
function addToCache(req, res, next) {
  const c = res.locals.rows[0]; // Newly created consumer from database
  log.debug(() => `Adding consumer to cache : ${JSON.stringify(c)}`);
  // Add consumer to cache
  csmerSvc.addToCache(c);
  next();
}

/**
 * Updates consumer tokens in cache after successful database update
 * Middleware in updateConsumer stack of PUT /consumers route
 *
 * @param {Object} req - Express request
 * @param {Object} req.body - Request body
 * @param {Array} req.body.rows - Array with updated consumer data
 *
 * @param {Object} res - Express response
 * @param {Object} res.locals - Response locals
 *
 * @param {Function} next - Express next function
 *
 * @modifies Updates in-memory consumer cache with new tokens
 *
 * INPUT:
 *   req.body.rows[0] = { id, accessToken, refreshToken }
 *
 * OUTPUT:
 *   Cache updated with new tokens for the consumer
 */
function updateCache(req, res, next) {
  const c = req.body.rows[0];
  log.debug(() => `Updating consumer ${c.id} in cache`);
  // Update consumer in cache
  const updatedC = csmerSvc.updateCache(
    c.id,
    c.accessToken,
    c.refreshToken,
    c.roles,
  );
  if (!updatedC)
    return next({
      status: 404,
      msg: "Consumer not updated in cache",
    });

  next();
}

/**
 * @param {import('express').Request} req - Express request object
 * @param {import('express').Response} res - Express response object
 * @param {import('express').NextFunction} next - Express next function
 */
function deleteFromCache(req, res, next) {
  const c = req.body.rows[0];
  log.debug(() => `Deleting consumer ${c.id} from cache`);
  csmerSvc.deleteFromCache(c.id);
  next();
}

export { addToCache, updateCache, deleteFromCache };
