// @ts-check
import { SQLEntity } from "@dwtechs/antity-pgsql";

/**
 * Read-only consumer entity used exclusively by `services/consumer.js` to warm
 * the in-memory session cache, which is keyed by access and refresh token.
 *
 * Kept separate from `consumer.js` because antity shares one SELECT column list
 * between `get()` (the admin search route) and `getCache()`. Tokens live here so
 * they never appear in a search response. Never mount this entity on a router.
 */
export default new SQLEntity("consumer", [
  {
    key: "id",
    type: "integer",
    min: null,
    max: null,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "userId",
    type: "integer",
    min: null,
    max: null,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "nickname",
    type: "string",
    min: 3,
    max: 30,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "accessToken",
    type: "jwt",
    min: 28,
    max: 8000,
    isTypeChecked: true,
    isFilterable: false,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "refreshToken",
    type: "jwt",
    min: 28,
    max: 8000,
    isTypeChecked: true,
    isFilterable: false,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "roles",
    type: "array",
    min: null,
    max: null,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "archived",
    type: "boolean",
    min: null,
    max: null,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
]);
