// @ts-check
import { SQLEntity } from "@dwtechs/antity-pgsql";

export default new SQLEntity("operation", [
  {
    key: "id",
    type: "integer",
    min: null,
    max: null,
    typeCheck: true,
    filter: true,
    need: [],
    operations: ["SELECT"],
    send: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "name",
    type: "string",
    min: 1,
    max: 50,
    typeCheck: true,
    filter: true,
    need: ["POST", "PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    send: true,
    validate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "description",
    type: "string",
    min: 0,
    max: 1000,
    typeCheck: true,
    filter: false,
    need: ["POST", "PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    send: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "archived",
    type: "boolean",
    min: null,
    max: null,
    typeCheck: true,
    filter: true,
    need: ["POST"],
    operations: ["SELECT"],
    send: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
]);
