// @ts-check
import { SQLEntity } from "@dwtechs/antity-pgsql";

export default new SQLEntity("preferences", [
  {
    key: "id",
    type: "integer",
    min: null,
    max: null,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "userId",
    type: "integer",
    min: null,
    max: null,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["POST"],
    operations: ["SELECT", "INSERT"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "resourceId",
    type: "integer",
    min: 1,
    max: null,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["POST"],
    operations: ["SELECT", "INSERT"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "resourceName",
    type: "string",
    min: 1,
    max: 60,
    isTypeChecked: false,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "name",
    type: "string",
    min: 1,
    max: 60,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["PUT", "POST"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "conf",
    type: "object",
    min: null,
    max: null,
    isTypeChecked: true,
    isFilterable: false,
    requiredFor: ["POST"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: false,
    sanitizer: null,
    normalizer: JSON.stringify,
    validator: null,
  },
  {
    key: "locked",
    type: "boolean",
    min: null,
    max: null,
    isTypeChecked: false,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "isActive",
    type: "boolean",
    min: null,
    max: null,
    isTypeChecked: false,
    isFilterable: false,
    requiredFor: ["PUT", "POST"],
    operations: ["INSERT", "UPDATE"],
    isPrivate: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  // {
  //   key: "creatorName",
  //   type: "string",
  //   min: 1,
  //   max: 100,
  //   isTypeChecked: false,
  //   isFilterable: false,
  //   requiredFor: [],
  //   operations: ["SELECT"],
  //   isPrivate: false,
  //   sanitizer: null,
  //   normalizer: null,
  //   validator: null,
  // },
  // {
  //   key: "updaterName",
  //   type: "string",
  //   min: 1,
  //   max: 100,
  //   isTypeChecked: false,
  //   isFilterable: false,
  //   requiredFor: [],
  //   operations: ["SELECT"],
  //   isPrivate: false,
  //   sanitizer: null,
  //   normalizer: null,
  //   validator: null,
  // },
  // {
  //   key: "createdAt",
  //   type: "string",
  //   min: null,
  //   max: null,
  //   isTypeChecked: false,
  //   isFilterable: false,
  //   requiredFor: [],
  //   operations: ["SELECT"],
  //   isPrivate: false,
  //   sanitizer: null,
  //   normalizer: null,
  //   validator: null,
  // },
  // {
  //   key: "updatedAt",
  //   type: "string",
  //   min: null,
  //   max: null,
  //   isTypeChecked: false,
  //   isFilterable: false,
  //   requiredFor: [],
  //   operations: ["SELECT"],
  //   isPrivate: false,
  //   sanitizer: null,
  //   normalizer: null,
  //   validator: null,
  // },
]);
