// @ts-check
import { SQLEntity } from "@dwtechs/antity-pgsql";

export default new SQLEntity("routes", [
  {
    key: "id",
    type: "integer",
    min: null,
    max: null,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "serviceId",
    type: "integer",
    min: null,
    max: null,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["POST", "PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "serviceName",
    type: "string",
    min: 2,
    max: 10,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "resourceId",
    type: "integer",
    min: null,
    max: null,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["POST", "PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "resourceName",
    type: "string",
    min: 2,
    max: 20,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "operations",
    type: "array",
    min: 1,
    max: 13,
    isTypeChecked: true,
    isFilterable: false,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "operationName",
    type: "array",
    min: 1,
    max: 13,
    isTypeChecked: true,
    isFilterable: false,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "pattern",
    type: "string",
    min: 1,
    max: 40,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["POST", "PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "url",
    type: "string",
    min: 1,
    max: 100,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "name",
    type: "string",
    min: 0,
    max: 50,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["POST", "PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "description",
    type: "string",
    min: 0,
    max: 200,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["POST", "PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "methodIds",
    type: "array",
    min: 1,
    max: 7,
    isTypeChecked: true,
    isFilterable: false,
    requiredFor: ["POST", "PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "methodNames",
    type: "array",
    min: 1,
    max: 7,
    isTypeChecked: true,
    isFilterable: false,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "protected",
    type: "boolean",
    min: null,
    max: null,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["POST", "PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "locked",
    type: "boolean",
    min: null,
    max: null,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "archived",
    type: "boolean",
    min: null,
    max: null,
    isTypeChecked: true,
    isFilterable: true,
    requiredFor: ["POST"],
    operations: ["SELECT"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "creatorName",
    type: "string",
    min: 1,
    max: 100,
    isTypeChecked: true,
    isFilterable: false,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "updaterName",
    type: "string",
    min: 1,
    max: 100,
    isTypeChecked: true,
    isFilterable: false,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "createdAt",
    type: "string",
    min: null,
    max: null,
    isTypeChecked: false,
    isFilterable: false,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "updatedAt",
    type: "string",
    min: null,
    max: null,
    isTypeChecked: false,
    isFilterable: false,
    requiredFor: [],
    operations: ["SELECT"],
    isPrivate: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
]);
