// @ts-check
import { SQLEntity } from "@dwtechs/antity-pgsql";

export default new SQLEntity("service", [
  {
    key: "id",
    type: "integer",
    min: 1,
    max: 999999999,
    typeCheck: true,
    filter: true,
    need: [],
    operations: ["SELECT"],
    send: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "name",
    type: "string",
    min: 1,
    max: 10,
    typeCheck: true,
    filter: true,
    need: ["POST", "PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    send: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "pattern",
    type: "string",
    min: 0,
    max: 1000,
    typeCheck: true,
    filter: true,
    need: ["POST", "PUT"],
    operations: ["SELECT", "INSERT", "UPDATE"],
    send: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "locked",
    type: "boolean",
    min: null,
    max: null,
    typeCheck: true,
    filter: true,
    need: [],
    operations: ["SELECT"],
    send: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
]);
