// @ts-check
import { SQLEntity } from "@dwtechs/antity-pgsql";

/**
 * Session entity configuration for database operations.
 * Defines validation rules, types, and constraints for session data.
 */
const sessionEntity = new SQLEntity("consumer", [
  {
    key: "id",
    type: "integer",
    min: null,
    max: null,
    typeCheck: true,
    filter: true,
    need: ["POST"],
    operations: ["SELECT"],
    send: false,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "userId",
    type: "integer",
    min: null,
    max: null,
    typeCheck: true,
    filter: true,
    need: ["POST"],
    operations: ["INSERT"],
    send: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "nickname",
    type: "string",
    min: 3,
    max: 30,
    typeCheck: true,
    filter: true,
    need: ["POST", "PUT"],
    operations: ["INSERT", "UPDATE"],
    send: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "accessToken",
    type: "jwt",
    min: 28,
    max: 8000,
    typeCheck: true,
    filter: false,
    need: ["POST", "PUT"],
    operations: ["INSERT", "UPDATE"],
    send: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "refreshToken",
    type: "jwt",
    min: 28,
    max: 8000,
    typeCheck: true,
    filter: false,
    need: ["POST", "PUT"],
    operations: ["INSERT", "UPDATE"],
    send: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
  {
    key: "roles",
    type: "array",
    min: null,
    max: null,
    typeCheck: true,
    filter: true,
    need: ["POST", "PUT"],
    operations: ["INSERT", "UPDATE"],
    send: true,
    sanitizer: null,
    normalizer: null,
    validator: null,
  },
]);

export default sessionEntity;
