name: ${APP_NAME}

services:
  gatelin:
    build:
      context: ${PWD}
      dockerfile: dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        TZ: ${TZ}
        LOCALE: ${LOCALE}
        HOME_PATH: ${HOME_PATH}
        NODE_VERSION: ${NODE_VERSION}
        NODE_ENV: ${NODE_ENV}
    image: gatelin:${NODE_ENV:-development}
    container_name: ${GATELIN_HOST}
    hostname: ${GATELIN_HOST}
    volumes:
      - ${PWD}/src:/usr/src/app/src
      - ${PWD}/tests:/usr/src/app/tests
      - ${PWD}/node/common/libs:/usr/src/libs
      - gateway_node_modules:/usr/src/app/node_modules
