name: ${APP_NAME}

secrets:
  apk_repository:
    environment: APK_REPOSITORY

services:
  admin:
    build:
      context: ${PWD}/admin
      dockerfile: dockerfile.prod
      secrets:
        - apk_repository
      args:
        NODE_VERSION: ${NODE_VERSION}
        CADDY_VERSION: ${CADDY_VERSION}
        TZ: ${TZ}
        UID: ${UID}
        GID: ${GID}
    image: ghcr.io/alten-group/gatelin-admin:${VERSION:-latest}
    container_name: ${ADMIN_HOST}
    hostname: ${ADMIN_HOST}
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "stack.name=${STACK_NAME}"
      - "traefik.http.routers.admin.rule=PathPrefix(`/admin`)"
      - "traefik.http.routers.admin.entrypoints=web"
      - "traefik.http.routers.admin.service=admin"
      - "traefik.http.services.admin.loadbalancer.server.port=8080"

networks:
  internal:
    name: ${APP_NAME}-internal-${ENV_NAME}
    driver: bridge
