name: ${APP_NAME}

x-logging-conf: &logging
  driver: "json-file"
  options: 
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

x-service-healthcheck: &healthcheck
  test: ["CMD", "node", "/usr/src/app/node_modules/health/test.js"]
  interval: 10s
  timeout: 5s
  retries: 5

# dockerfile mount during build
x-secret-args: &secretArgs
  secrets:
    - apt_repository
    - apk_repository
    - npmrc

# mount for run
x-secret-mount: &secretMount
  - source: npmrc
    target: /home/user/.npmrc

x-default-args: &defaultArgs
  UID: ${UID}
  GID: ${GID}
  TZ: ${TZ}
  LOCALE: ${LOCALE}
  HOME_PATH: ${HOME_PATH}

x-default-envs: &defaultEnvs
  PORT: ${DEFAULT_PORT}
  TZ: ${TZ}

x-resources-limits:
  - &pgsqlLimits
    cpus: ${PGSQL_LIMIT_CPUS}
    mem_limit: ${PGSQL_LIMIT_MEM}
  - &nodeLimits
    cpus: ${NODE_LIMIT_CPUS}
    mem_limit: ${NODE_LIMIT_MEM}
  - &minLimits
    cpus: ${MIN_LIMIT_CPUS}
    mem_limit: ${MIN_LIMIT_MEM}


services:

  # postgres:
  #   build:
  #     context: ${PWD}/db/pgsql
  #     dockerfile: dockerfile
  #     args:
  #       POSTGRES_VERSION: ${POSTGRES_VERSION}
  #   profiles: ["dev", "minimal", "mail", "scraper", "monitor"]
  #   container_name: ${POSTGRES_HOST}
  #   hostname: ${POSTGRES_HOST}
  #   environment:
  #     TZ: ${TZ}
  #     POSTGRES_DBS: ${POSTGRES_DBS}
  #     POSTGRES_USER: ${POSTGRES_ROOT_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_ROOT_PWD}
  #     #liquibase
  #     LIQUIBASE_USER: ${LIQUIBASE_DB_USER}
  #     LIQUIBASE_PWD: ${LIQUIBASE_DB_PWD}
  #     # ms_user
  #     MSUSER_USER: ${MSUSER_DB_USER}
  #     MSUSER_PWD: ${MSUSER_DB_PWD}
  #     # ms_gateway
  #     MSGATEWAY_USER: ${MSGATEWAY_DB_USER}
  #     MSGATEWAY_PWD: ${MSGATEWAY_DB_PWD}
  #     # ms_notif
  #     MSNOTIF_USER: ${MSNOTIF_DB_USER}
  #     MSNOTIF_PWD: ${MSNOTIF_DB_PWD}
  #     # ms_mail
  #     MSMAIL_USER: ${MSMAIL_DB_USER}
  #     MSMAIL_PWD: ${MSMAIL_DB_PWD}
  #     # ms_cron
  #     MSCRON_USER: ${MSCRON_DB_USER}
  #     MSCRON_PWD: ${MSCRON_DB_PWD}
  #   stdin_open: true
  #   tty: true
  #   networks:
  #     - internal
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "${POSTGRES_ROOT_USER}", "-d", "${MSUSER_DB_NAME}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #   logging: *logging
  #   <<: *pgsqlLimits


  postgis:
    platform: linux/amd64
    build:
      context: ${PWD}/db/postgis
      dockerfile: dockerfile
      args:
        - POSTGIS_VERSION=${POSTGIS_VERSION}
    profiles: ["dev", "minimal", "cron", "mail", "notif","scraper", "monitor"]
    container_name: ${POSTGIS_HOST}
    hostname: ${POSTGIS_HOST}
    environment:
      TZ: ${TZ}
      POSTGRES_DBS: ${POSTGIS_DBS}
      POSTGRES_USER: ${POSTGIS_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGIS_ROOT_PWD}
      #liquibase
      LIQUIBASE_USER: ${LIQUIBASE_DB_USER}
      LIQUIBASE_PWD: ${LIQUIBASE_DB_PWD}
      # ms_user
      MSUSER_USER: ${MSUSER_DB_USER}
      MSUSER_PWD: ${MSUSER_DB_PWD}
      # ms_gateway
      MSGATEWAY_USER: ${MSGATEWAY_DB_USER}
      MSGATEWAY_PWD: ${MSGATEWAY_DB_PWD}
      # ms_notif
      MSNOTIF_USER: ${MSNOTIF_DB_USER}
      MSNOTIF_PWD: ${MSNOTIF_DB_PWD}
      # ms_mail
      MSMAIL_USER: ${MSMAIL_DB_USER}
      MSMAIL_PWD: ${MSMAIL_DB_PWD}
      # ms_cron
      MSCRON_USER: ${MSCRON_DB_USER}
      MSCRON_PWD: ${MSCRON_DB_PWD}
      #ms_event
      MSEVENT_USER: ${MSEVENT_DB_USER}
      MSEVENT_PWD: ${MSEVENT_DB_PWD}
    stdin_open: true
    tty: true
    networks:
      - internal
    volumes:
      - postgis_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGIS_ROOT_USER}", "-d", "${MSEVENT_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 3
    logging: *logging
    <<: *pgsqlLimits

  ms_gateway_migration:
    build:
      context: ${PWD}/db/liquibase
      dockerfile: dockerfile
      <<: *secretArgs
      args:
        LIQUIBASE_VERSION: ${LIQUIBASE_VERSION}
    secrets: *secretMount
    container_name: ${MSGATEWAY_MIGRATION_HOST}
    hostname: ${MSGATEWAY_MIGRATION_HOST}
    profiles: ["dev", "minimal"]
    environment:
      <<: *defaultEnvs
      LIQUIBASE_COMMAND_USERNAME: ${LIQUIBASE_DB_USER}
      LIQUIBASE_COMMAND_PASSWORD: ${LIQUIBASE_DB_PWD}
      DB_HOST: ${POSTGIS_HOST}
      DB_PORT: ${POSTGIS_PORT}
      DB_NAME: ${MSGATEWAY_DB_NAME}
      DB_USER: ${MSGATEWAY_DB_USER}
      DB_PWD: ${MSGATEWAY_DB_PWD}
      UPDATE: ${LIQUIBASE_UPDATE}
      ROLLBACK: ${LIQUIBASE_ROLLBACK}
      SNAPSHOT: snapshot/snapshot${LIQUIBASE_SNAPSHOT}
      LIQUIBASE_LOG_LEVEL: ${LIQUIBASE_LOG_LEVEL}
      LIQUIBASE_COMMAND_CONTEXTS: ${LIQUIBASE_COMMAND_CONTEXTS}
    networks:
      - internal  
    depends_on:
      postgis:
        condition: service_healthy
    volumes:
      - ${PWD}/db/liquibase/gateway/:/liquibase/changelog


  ms_gateway:
    build:
      context: ${PWD}/node
      dockerfile: common/dockerfile
      <<: *secretArgs
      args:
        <<: *defaultArgs
        NODE_VERSION: ${MSGATEWAY_NODE_VERSION} 
        NODE_ENV: ${NODE_ENV} 
        FOLDER: ${MSGATEWAY_FOLDER}
    secrets: *secretMount
    container_name: ${MSGATEWAY_HOST}
    hostname: ${MSGATEWAY_HOST}
    profiles: ["dev", "minimal"]
    environment:
      <<: *defaultEnvs
      MSAUTH_URL: ${MSAUTH_URL}
      MSUSER_URL: ${MSUSER_URL}
      DB_HOST: ${POSTGIS_HOST}
      DB_NAME: ${MSGATEWAY_DB_NAME}
      DB_USER: ${MSGATEWAY_DB_USER}
      DB_PWD: ${MSGATEWAY_DB_PWD}
      TOKEN_SECRET: ${MSUSER_TOKEN_SECRET}
      PWD_SECRET: ${MSUSER_PWD_SECRET}
      APP_NAME: ${APP_NAME}
      ENV_NAME: ${ENV_NAME}
      SERVER_SCHEME: ${SERVER_SCHEME}
      PORT: ${DEFAULT_PORT}
      SERVICE_NAME: ${MSGATEWAY_HOST}
      ACCESS_TOKEN_DURATION: ${MSGATEWAY_ACCESS_TOKEN_DURATION}
      REFRESH_TOKEN_DURATION: ${MSGATEWAY_REFRESH_TOKEN_DURATION}
      PWD_MIN_LENGTH_POLICY: ${MSGATEWAY_PWD_MIN_LENGTH_LEGACY}
      PWD_MAX_LENGTH_POLICY: ${MSGATEWAY_PWD_MAX_LENGTH_LEGACY}
      PWD_NUMBERS_POLICY: ${MSGATEWAY_PWD_NUMBERS_LEGACY}
      PWD_UPPERCASE_POLICY: ${MSGATEWAY_PWD_UPPERCASE_LEGACY}
      PWD_LOWERCASE_POLICY: ${MSGATEWAY_PWD_LOWERCASE_LEGACY}
      PWD_SYMBOLS_POLICY: ${MSGATEWAY_PWD_SYMBOLS_LEGACY}
    networks:
      - internal    
    depends_on:
      postgis:
        condition: service_healthy
      # ms_user:
      #   condition: service_healthy
      ms_gateway_migration:
        condition: service_completed_successfully
    volumes:
      - ${PWD}/node/gateway/src:/usr/src/app/src
      - ${PWD}/node/gateway/tests:/usr/src/app/tests
      - ${PWD}/node/gateway/dist:/usr/src/app/dist
      - ${PWD}/node/gateway/assets/public/:/opt/docker-entrypoint/public
      - ${PWD}/node/common/entrypoint.sh:/opt/docker-entrypoint/entrypoint.sh
      - ${PWD}/node/common/libs:/usr/src/libs
      - gateway_node_modules:/usr/src/app/node_modules
    labels:
      - "traefik.enable=true"
      - "stack.name=${STACK_NAME}"
      - "traefik.http.routers.gateway.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.gateway.entrypoints=web"
      - "traefik.http.routers.gateway.service=gateway"
      - "traefik.http.routers.gateway.middlewares=strip-prefix"
      - "traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.strip-prefix.stripprefix.forceSlash=false"
      - "traefik.http.services.gateway.loadBalancer.server.port=${DEFAULT_PORT}"
    healthcheck: *healthcheck
    logging: *logging
    <<: *nodeLimits

  adminer:
    image: ${ADMINER_VERSION}
    container_name: ${ADMINER_HOST}
    hostname:  ${ADMINER_HOST}
    profiles: ["dev", "adminer"]
    networks:
      - internal
    environment:
      ADMINER_DEFAULT_SERVER: ${POSTGIS_HOST}
      ADMINER_DEFAULT_DRIVER: pgsql
      ADMINER_DESIGN: pappu687
    labels:
      - "traefik.enable=true"
      - "stack.name=${STACK_NAME}"
      - "traefik.http.routers.adminer.rule=PathPrefix(`/adminer`)"
      - "traefik.http.routers.adminer.entrypoints=web"
      - "traefik.http.routers.adminer.service=adminer"
      - "traefik.http.routers.adminer.middlewares=adminer"
      - "traefik.http.services.adminer.loadbalancer.server.port=${ADMINER_PORT}"
      - "traefik.http.middlewares.adminer.stripprefix.prefixes=/adminer"
    <<: *minLimits


networks:
  internal:
    name: ${APP_NAME}-internal-${ENV_NAME}
    driver: bridge 
  # external:
  #   name: ${APP_NAME}-external-${ENV_NAME}
  #   driver: bridge


secrets:
  apk_repository:
    environment: APK_REPOSITORY
  apt_repository:
    environment: APT_REPOSITORY
  npmrc:
    environment: NPMRC


volumes:
  # postgres_data:
  #   driver: local
  postgis_data:
    driver: local
  gateway_node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/node/gateway/node_modules