name: ${APP_NAME}

x-logging-conf: &logging
  driver: "json-file"
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

x-service-healthcheck: &healthcheck
  test: ["CMD", "node", "/usr/src/app/node_modules/health/test.js"]
  interval: 10s
  timeout: 5s
  retries: 5

# dockerfile mount during build
x-secret-args: &secretArgs
  secrets:
    - apt_repository
    - apk_repository
    - npmrc

# mount for run
x-secret-mount: &secretMount
  - source: npmrc
    target: /home/user/.npmrc

x-default-args: &defaultArgs
  UID: ${UID}
  GID: ${GID}
  TZ: ${TZ}
  LOCALE: ${LOCALE}
  HOME_PATH: ${HOME_PATH}
  
x-default-envs: &defaultEnvs
  PORT: ${DEFAULT_PORT}
  TZ: ${TZ}

services:

  postgres:
    image: ${REPO_URL}:${REPO_PORT}/${APP_NAME}_postgres:${APP_VERSION}
    build:
      context: ${PWD}/db/pgsql
      dockerfile: dockerfile
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    profiles: ["prod", "db"]
    container_name: ${POSTGRES_HOST}
    hostname: ${POSTGRES_HOST}
    environment:
      TZ: ${TZ}
      POSTGRES_DBS: ${POSTGRES_DBS}
      POSTGRES_USER: ${POSTGRES_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PWD}
      #liquibase
      LIQUIBASE_USER: ${LIQUIBASE_DB_USER}
      LIQUIBASE_PWD: ${LIQUIBASE_DB_PWD}
      # ms_user
      MSUSER_USER: ${MSUSER_DB_USER}
      MSUSER_PWD: ${MSUSER_DB_PWD}
      # ms_gateway
      MSGATEWAY_USER: ${MSGATEWAY_DB_USER}
      MSGATEWAY_PWD: ${MSGATEWAY_DB_PWD}
      # ms_notif
      MSNOTIF_USER: ${MSNOTIF_DB_USER}
      MSNOTIF_PWD: ${MSNOTIF_DB_PWD}
      # ms_mail
      MSMAIL_USER: ${MSMAIL_DB_USER}
      MSMAIL_PWD: ${MSMAIL_DB_PWD}
      # ms_cron
      MSCRON_USER: ${MSCRON_DB_USER}
      MSCRON_PWD: ${MSCRON_DB_PWD}
    stdin_open: true
    tty: true
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_ROOT_USER}", "-d", "${MSUSER_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 3
    logging: *logging


  postgis:
    image: ${REPO_URL}:${REPO_PORT}/${APP_NAME}_postgis:${APP_VERSION}
    build:
      context: ${PWD}/db/postgis
      dockerfile: dockerfile
      args:
        - POSTGIS_VERSION=${POSTGIS_VERSION}
    profiles: ["prod", "db"]
    container_name: ${POSTGIS_HOST}
    hostname: ${POSTGIS_HOST}
    environment:
      TZ: ${TZ}
      POSTGRES_DBS: ${POSTGIS_DBS}
      POSTGRES_USER: ${POSTGIS_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGIS_ROOT_PWD}
      #liquibase
      LIQUIBASE_USER: ${LIQUIBASE_DB_USER}
      LIQUIBASE_PWD: ${LIQUIBASE_DB_PWD}
      #ms_event
      MSEVENT_USER: ${MSEVENT_DB_USER}
      MSEVENT_PWD: ${MSEVENT_DB_PWD}
    stdin_open: true
    tty: true
    networks:
      - internal
    volumes:
      - postgis_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGIS_ROOT_USER}", "-d", "${MSEVENT_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 3
    logging: *logging


  ms_gateway_migration:
    build:
      context: ${PWD}/db/liquibase
      dockerfile: dockerfile
      <<: *secretArgs
      args:
        LIQUIBASE_VERSION: ${LIQUIBASE_VERSION}
    secrets: *secretMount
    container_name: ${MSGATEWAY_MIGRATION_HOST}
    hostname: ${MSGATEWAY_MIGRATION_HOST}
    profiles: ["dev", "minimal"]
    environment:
      <<: *defaultEnvs
      LIQUIBASE_COMMAND_USERNAME: ${LIQUIBASE_DB_USER}
      LIQUIBASE_COMMAND_PASSWORD: ${LIQUIBASE_DB_PWD}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${MSGATEWAY_DB_NAME}
      DB_USER: ${MSGATEWAY_DB_USER}
      DB_PWD: ${MSGATEWAY_DB_PWD}
      UPDATE: ${LIQUIBASE_UPDATE}
      ROLLBACK: ${LIQUIBASE_ROLLBACK}
      SNAPSHOT: snapshot/snapshot${LIQUIBASE_SNAPSHOT}
      LIQUIBASE_LOG_LEVEL: ${LIQUIBASE_LOG_LEVEL}
      LIQUIBASE_COMMAND_CONTEXTS: ${LIQUIBASE_COMMAND_CONTEXTS}
    networks:
      - internal  
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${PWD}/db/liquibase/gateway/:/liquibase/changelog

  ms_user_migration:
    build:
      context: ${PWD}/db/liquibase
      dockerfile: dockerfile
      <<: *secretArgs
      args:
        LIQUIBASE_VERSION: ${LIQUIBASE_VERSION}
    secrets: *secretMount
    container_name: ${MSUSER_MIGRATION_HOST}
    hostname: ${MSUSER_MIGRATION_HOST}
    profiles: ["dev", "minimal"]
    environment:
      <<: *defaultEnvs
      LIQUIBASE_COMMAND_USERNAME: ${LIQUIBASE_DB_USER}
      LIQUIBASE_COMMAND_PASSWORD: ${LIQUIBASE_DB_PWD}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${MSUSER_DB_NAME}
      DB_USER: ${MSUSER_DB_USER}
      DB_PWD: ${MSUSER_DB_PWD}
      UPDATE: ${LIQUIBASE_UPDATE}
      ROLLBACK: ${LIQUIBASE_ROLLBACK}
      SNAPSHOT: snapshot/snapshot${LIQUIBASE_SNAPSHOT}
      LIQUIBASE_LOG_LEVEL: ${LIQUIBASE_LOG_LEVEL}
      LIQUIBASE_COMMAND_CONTEXTS: ${LIQUIBASE_COMMAND_CONTEXTS}
    networks:
      - internal  
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${PWD}/db/liquibase/user/:/liquibase/changelog


  ms_notif_migration:
    build:
      context: ${PWD}/db/liquibase
      dockerfile: dockerfile
      <<: *secretArgs
      args:
        LIQUIBASE_VERSION: ${LIQUIBASE_VERSION}
    secrets: *secretMount
    container_name: ${MSNOTIF_MIGRATION_HOST}
    hostname: ${MSNOTIF_MIGRATION_HOST}
    profiles: ["dev"]
    environment:
      <<: *defaultEnvs
      LIQUIBASE_COMMAND_USERNAME: ${LIQUIBASE_DB_USER}
      LIQUIBASE_COMMAND_PASSWORD: ${LIQUIBASE_DB_PWD}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${MSNOTIF_DB_NAME}
      DB_USER: ${MSNOTIF_DB_USER}
      DB_PWD: ${MSNOTIF_DB_PWD}
      UPDATE: ${LIQUIBASE_UPDATE}
      ROLLBACK: ${LIQUIBASE_ROLLBACK}
      SNAPSHOT: snapshot/snapshot${LIQUIBASE_SNAPSHOT}
      LIQUIBASE_LOG_LEVEL: ${LIQUIBASE_LOG_LEVEL}
      LIQUIBASE_COMMAND_CONTEXTS: ${LIQUIBASE_COMMAND_CONTEXTS}
    networks:
      - internal  
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${PWD}/db/liquibase/notif/:/liquibase/changelog


  ms_mail_migration:
    build:
      context: ${PWD}/db/liquibase
      dockerfile: dockerfile
      <<: *secretArgs
      args:
        LIQUIBASE_VERSION: ${LIQUIBASE_VERSION}
    secrets: *secretMount
    container_name: ${MSMAIL_MIGRATION_HOST}
    hostname: ${MSMAIL_MIGRATION_HOST}
    profiles: ["dev", "notif"]
    environment:
      <<: *defaultEnvs
      LIQUIBASE_COMMAND_USERNAME: ${LIQUIBASE_DB_USER}
      LIQUIBASE_COMMAND_PASSWORD: ${LIQUIBASE_DB_PWD}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${MSMAIL_DB_NAME}
      DB_USER: ${MSMAIL_DB_USER}
      DB_PWD: ${MSMAIL_DB_PWD}
      UPDATE: ${LIQUIBASE_UPDATE}
      ROLLBACK: ${LIQUIBASE_ROLLBACK}
      SNAPSHOT: snapshot/snapshot${LIQUIBASE_SNAPSHOT}
      LIQUIBASE_LOG_LEVEL: ${LIQUIBASE_LOG_LEVEL}
      LIQUIBASE_COMMAND_CONTEXTS: ${LIQUIBASE_COMMAND_CONTEXTS}
    networks:
      - internal  
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${PWD}/db/liquibase/mail/:/liquibase/changelog


  ms_cron_migration:
    build:
      context: ${PWD}/db/liquibase
      dockerfile: dockerfile
      <<: *secretArgs
      args:
        LIQUIBASE_VERSION: ${LIQUIBASE_VERSION}
    secrets: *secretMount
    container_name: ${MSCRON_MIGRATION_HOST}
    hostname: ${MSCRON_MIGRATION_HOST}
    profiles: ["dev", "cron"]
    environment:
      <<: *defaultEnvs
      LIQUIBASE_COMMAND_USERNAME: ${LIQUIBASE_DB_USER}
      LIQUIBASE_COMMAND_PASSWORD: ${LIQUIBASE_DB_PWD}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${MSCRON_DB_NAME}
      DB_USER: ${MSCRON_DB_USER}
      DB_PWD: ${MSCRON_DB_PWD}
      UPDATE: ${LIQUIBASE_UPDATE}
      ROLLBACK: ${LIQUIBASE_ROLLBACK}
      SNAPSHOT: snapshot/snapshot${LIQUIBASE_SNAPSHOT}
      LIQUIBASE_LOG_LEVEL: ${LIQUIBASE_LOG_LEVEL}
      LIQUIBASE_COMMAND_CONTEXTS: ${LIQUIBASE_COMMAND_CONTEXTS}
    networks:
      - internal  
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${PWD}/db/liquibase/cron/:/liquibase/changelog


  ms_event_migration:
    build:
      context: ${PWD}/db/liquibase
      dockerfile: dockerfile
      <<: *secretArgs
      args:
        LIQUIBASE_VERSION: ${LIQUIBASE_VERSION}
    secrets: *secretMount
    container_name: ${MSEVENT_MIGRATION_HOST}
    hostname: ${MSEVENT_MIGRATION_HOST}
    profiles: ["dev", "minimal"]
    environment:
      <<: *defaultEnvs
      LIQUIBASE_COMMAND_USERNAME: ${LIQUIBASE_DB_USER}
      LIQUIBASE_COMMAND_PASSWORD: ${LIQUIBASE_DB_PWD}
      DB_HOST: ${POSTGIS_HOST}
      DB_PORT: ${POSTGIS_PORT}
      DB_NAME: ${MSEVENT_DB_NAME}
      DB_USER: ${MSEVENT_DB_USER}
      DB_PWD: ${MSEVENT_DB_PWD}
      UPDATE: ${LIQUIBASE_UPDATE}
      ROLLBACK: ${LIQUIBASE_ROLLBACK}
      SNAPSHOT: snapshot/snapshot${LIQUIBASE_SNAPSHOT}
      LIQUIBASE_LOG_LEVEL: ${LIQUIBASE_LOG_LEVEL}
      LIQUIBASE_COMMAND_CONTEXTS: ${LIQUIBASE_COMMAND_CONTEXTS}
    networks:
      - internal  
    depends_on:
      postgis:
        condition: service_healthy
    volumes:
      - ${PWD}/db/liquibase/event/:/liquibase/changelog


  ms_gateway:
    image: ${REPO_URL}:${REPO_PORT}/${APP_NAME}_${MSGATEWAY_SERVICE_NAME}:${APP_VERSION}
    build:
      context: ${PWD}/node
      dockerfile: common/dockerfile.prod
      <<: *secretArgs
      args:
        <<: *defaultArgs
        NODE_VERSION: ${MSGATEWAY_NODE_VERSION} 
        NODE_ENV: ${NODE_ENV} 
        FOLDER: ${MSGATEWAY_FOLDER}
    secrets: *secretMount
    container_name: ${MSGATEWAY_HOST}
    hostname: ${MSGATEWAY_HOST}
    profiles: ["prod", "back"]
    environment:
      <<: *defaultEnvs
      MSUSER_URL: ${MSUSER_URL}
      DB_HOST: ${POSTGRES_HOST}
      DB_NAME: ${MSGATEWAY_DB_NAME}
      DB_USER: ${MSGATEWAY_DB_USER}
      DB_PWD: ${MSGATEWAY_DB_PWD}
      TOKEN_SECRET: ${MSUSER_TOKEN_SECRET}
      PWD_SECRET: ${MSUSER_PWD_SECRET}
      APP_NAME: ${APP_NAME}
      ENV_NAME: ${ENV_NAME}
      SERVER_SCHEME: ${SERVER_SCHEME}
      DEFAULT_PORT: ${DEFAULT_PORT}
      SERVICE_NAME: ${MSGATEWAY_HOST}
    networks:
      - internal    
    depends_on:
      postgres:
        condition: service_healthy
      ms_user:
        condition: service_healthy
    healthcheck: *healthcheck
    logging: *logging

  ms_user:
    image: ${REPO_URL}:${REPO_PORT}/${APP_NAME}_${MSUSER_SERVICE_NAME}:${APP_VERSION}
    build:
      context: ${PWD}/node
      dockerfile: common/dockerfile.prod
      <<: *secretArgs
      args:
        <<: *defaultArgs
        NODE_VERSION: ${MSUSER_NODE_VERSION}
        NODE_ENV: ${NODE_ENV}
        FOLDER: ${MSUSER_FOLDER}
    secrets: *secretMount
    container_name: ${MSUSER_HOST}
    hostname: ${MSUSER_HOST}
    profiles: ["prod", "back"]
    environment:
      <<: *defaultEnvs
      MSMAIL_URL: ${MSMAIL_URL}
      IMG_FOLDER: ./src/public/img/
      PUBLIC_IMG_FOLDER: user/img/
      DB_HOST: ${POSTGRES_HOST}
      DB_NAME: ${MSUSER_DB_NAME}
      DB_USER: ${MSUSER_DB_USER}
      DB_PWD: ${MSUSER_DB_PWD}
      TOKEN_SECRET: ${MSUSER_TOKEN_SECRET}
      PWD_SECRET: ${MSUSER_PWD_SECRET}
      PWD_MIN_LENGTH: ${MSUSER_PWD_MIN_LENGTH}
      PWD_MAX_LENGTH: ${MSUSER_PWD_MAX_LENGTH}
      PWD_AUTO_LENGTH: ${MSUSER_PWD_AUTO_LENGTH}
      PWD_AUTO_NUMBERS: ${MSUSER_PWD_AUTO_NUMBERS}
      PWD_AUTO_UPPERCASE: ${MSUSER_PWD_AUTO_UPPERCASE}
      PWD_AUTO_LOWERCASE: ${MSUSER_PWD_AUTO_LOWERCASE}
      PWD_AUTO_SYMBOLS: ${MSUSER_PWD_AUTO_SYMBOLS}
      PWD_AUTO_STRICT: ${MSUSER_PWD_AUTO_STRICT}
      PWD_AUTO_EXCLUDE_SIMILAR_CHARS: ${MSUSER_PWD_AUTO_EXCLUDE_SIMILAR_CHARS}
      FIRSTNAME_MIN_LENGTH: ${MSUSER_FIRSTNAME_MIN_LENGTH}
      LASTNAME_MIN_LENGTH: ${MSUSER_LASTNAME_MIN_LENGTH}
      FIRSTNAME_MAX_LENGTH: ${MSUSER_FIRSTNAME_MAX_LENGTH}
      LASTNAME_MAX_LENGTH: ${MSUSER_LASTNAME_MAX_LENGTH}
      ACCESS_TOKEN_DURATION: ${MSUSER_ACCESS_TOKEN_DURATION}
      REFRESH_TOKEN_DURATION: ${MSUSER_REFRESH_TOKEN_DURATION}
      APP_NAME: ${APP_NAME}
      APP_WEBSITE: ${APP_WEBSITE}
      SERVICE_NAME: ${MSUSER_HOST}
    networks:
      - internal  
    volumes:
      - user_assets:/usr/src/app/src/public
    healthcheck: *healthcheck
    logging: *logging


  ms_notif:
    image: ${REPO_URL}:${REPO_PORT}/${APP_NAME}_${MSNOTIF_SERVICE_NAME}:${APP_VERSION}
    build:
      context: ${PWD}/node
      dockerfile: common/dockerfile.prod
      <<: *secretArgs
      args:
        <<: *defaultArgs
        NODE_VERSION: ${MSNOTIF_NODE_VERSION}
        NODE_ENV: ${NODE_ENV}
        PORT: ${DEFAULT_PORT}
        FOLDER: ${MSNOTIF_FOLDER}
    secrets: *secretMount
    container_name: ${MSNOTIF_HOST}
    hostname: ${MSNOTIF_HOST}
    profiles: ["prod", "back"]
    environment:
      GATEWAY_HOST: ${KONG_HOST}
      GATEWAY_PORT: ${KONG_ADMIN_PORT}
      DB_HOST: ${POSTGRES_HOST}
      DB_NAME: ${MSNOTIF_DB_NAME}
      DB_USER: ${MSNOTIF_DB_USER}
      DB_PWD: ${MSNOTIF_DB_PWD}
      SERVICE_NAME: ${MSNOTIF_HOST}
    networks:
      - internal    
    healthcheck: *healthcheck
    logging: *logging
  

  ms_cron:
    image: ${REPO_URL}:${REPO_PORT}/${APP_NAME}_${MSCRON_SERVICE_NAME}:${APP_VERSION}
    build:
      context: ${PWD}/node
      dockerfile: common/dockerfile.prod
      <<: *secretArgs
      args:
        <<: *defaultArgs
        NODE_VERSION: ${MSCRON_NODE_VERSION}
        NODE_ENV: ${NODE_ENV}
        FOLDER: ${MSCRON_FOLDER}
    secrets: *secretMount
    container_name: ${MSCRON_HOST}
    hostname: ${MSCRON_HOST}
    profiles: ["prod", "back"]
    environment:
      <<: *defaultEnvs
      DB_HOST: ${POSTGRES_HOST}
      DB_NAME: ${MSCRON_DB_NAME}
      DB_USER: ${MSCRON_DB_USER}
      DB_PWD: ${MSCRON_DB_PWD}
      SERVICE_NAME: ${MSCRON_HOST}
      SERVER_SCHEME: ${SERVER_SCHEME}
      DEFAULT_PORT: ${DEFAULT_PORT}
      APP_NAME: ${APP_NAME}
      ENV_NAME: ${ENV_NAME}
    networks:
      - internal    
    healthcheck: *healthcheck
    logging: *logging
  

  ms_mail:
    image: ${REPO_URL}:${REPO_PORT}/${APP_NAME}_${MSMAIL_SERVICE_NAME}:${APP_VERSION}
    build:
      context: ${PWD}/node
      dockerfile: common/dockerfile.prod
      <<: *secretArgs
      args:
        <<: *defaultArgs
        NODE_VERSION: ${MSMAIL_NODE_VERSION}
        NODE_ENV: ${NODE_ENV}
        FOLDER: ${MSMAIL_FOLDER}
    secrets: *secretMount
    container_name: ${MSMAIL_HOST}
    hostname: ${MSMAIL_HOST}
    profiles: ["prod", "back"]
    environment:
      <<: *defaultEnvs
      GATEWAY_HOST: ${KONG_HOST}
      GATEWAY_PORT: ${KONG_ADMIN_PORT}
      AMQP_HOST: ${AMQP_HOST}
      AMQP_VHOST: ${AMQP_DEFAULT_VHOST}
      AMQP_PORT: ${AMQP_LISTENERS_TCP_DEFAULT}
      AMQP_PROTOCOL: ${AMQP_PROTOCOL}
      AMQP_HEARTBEAT: ${AMQP_HEARTBEAT}
      AMQP_RECONNECTION_LIMIT: ${AMQP_RECONNECTION_LIMIT}
      AMQP_QUEUE: ${MSMAIL_AMQP_QUEUE}
      AMQP_USER: ${AMQP_DEFAULT_USER}
      AMQP_PASSWORD: ${AMQP_DEFAULT_PASSWORD}
      DB_HOST: ${POSTGRES_HOST}
      DB_NAME: ${MSMAIL_DB_NAME}
      DB_USER: ${MSMAIL_DB_USER}
      DB_PWD: ${MSMAIL_DB_PWD}
      SMTP_HOST: ${MSMAIL_SMTP_HOST}
      SMTP_PORT: ${MSMAIL_SMTP_PORT}
      SMTP_FROM: ${MSMAIL_SMTP_FROM}
      SMTP_USER: ${MSMAIL_SMTP_USER}
      SMTP_PASS: ${MSMAIL_SMTP_PASS}
      TPL_FOLDER: ./src/templates/
      SYSTEM_EMAIL: ${SYSTEM_EMAIL}
      # PUBLIC_TPL_FOLDER: user/img/
      SERVICE_NAME: ${MSMAIL_HOST}
    networks:
      - internal    
    volumes:
      - mail_assets:/usr/src/app/src/public
      # - ${PWD}/node/mail/assets/templates/:/opt/docker-entrypoint/templates
    healthcheck: *healthcheck
    logging: *logging

  ms_event:
    image: ${REPO_URL}:${REPO_PORT}/${APP_NAME}_${MSEVENT_SERVICE_NAME}:${APP_VERSION}
    build:
      context: ${PWD}/node
      dockerfile: common/dockerfile.prod
      <<: *secretArgs
      args:
        <<: *defaultArgs
        NODE_VERSION: ${MSEVENT_NODE_VERSION}
        NODE_ENV: ${NODE_ENV}
        FOLDER: ${MSEVENT_FOLDER}
    secrets: *secretMount
    container_name: ${MSEVENT_HOST}
    hostname: ${MSEVENT_HOST}
    profiles: ["prod", "back"]
    environment:
      GATEWAY_HOST: ${KONG_HOST}
      GATEWAY_PORT: ${KONG_ADMIN_PORT}
      IMG_FOLDER: ./src/public/img/
      PUBLIC_IMG_FOLDER: event/img/
      DB_HOST: ${POSTGIS_HOST}
      DB_NAME: ${MSEVENT_DB_NAME}
      DB_USER: ${MSEVENT_DB_USER}
      DB_PWD: ${MSEVENT_DB_PWD}
      SERVICE_NAME: ${MSEVENT_HOST}
    networks:
      - internal
    volumes:
      - event_assets:/usr/src/app/src/public
    healthcheck: *healthcheck
    logging: *logging


  ms_excel:
    image: ${REPO_URL}:${REPO_PORT}/${APP_NAME}_${MSEXCEL_SERVICE_NAME}:${APP_VERSION}
    build:
      context: ${PWD}/node
      dockerfile: common/dockerfile.prod
      <<: *secretArgs
      args:
        <<: *defaultArgs
        NODE_VERSION: ${MSEXCEL_NODE_VERSION}
        NODE_ENV: ${NODE_ENV}
        FOLDER: ${MSEXCEL_FOLDER}
    secrets: *secretMount
    container_name: ${MSEXCEL_HOST}
    hostname: ${MSEXCEL_HOST}
    profiles: ["dev"]
    environment:
      <<: *defaultEnvs
      AMQP_HOST: ${AMQP_HOST}
      AMQP_VHOST: ${AMQP_DEFAULT_VHOST}
      AMQP_PORT: ${AMQP_LISTENERS_TCP_DEFAULT}
      AMQP_PROTOCOL: ${AMQP_PROTOCOL}
      AMQP_HEARTBEAT: ${AMQP_HEARTBEAT}
      AMQP_RECONNECTION_LIMIT: ${AMQP_RECONNECTION_LIMIT}
      AMQP_QUEUE: ${MSEXCEL_AMQP_QUEUE}
      AMQP_USER: ${AMQP_DEFAULT_USER}
      AMQP_PASSWORD: ${AMQP_DEFAULT_PASSWORD}
      SERVICE_NAME: ${MSEXCEL_HOST}
    networks:
      - internal 
    healthcheck: *healthcheck
    logging: *logging
 

  ms_scraper:
    image: ${REPO_URL}:${REPO_PORT}/${APP_NAME}_${MSSCRAPER_SERVICE_NAME}:${APP_VERSION}
    build:
      context: ${PWD}/node
      dockerfile: ${MSSCRAPER_FOLDER}/dockerfile.prod
      <<: *secretArgs
      args:
        <<: *defaultArgs
        NODE_VERSION: ${MSSCRAPER_NODE_VERSION}
        NODE_ENV: ${NODE_ENV}
        FOLDER: ${MSSCRAPER_FOLDER}
    secrets: *secretMount
    container_name: ${MSSCRAPER_HOST}
    hostname: ${MSSCRAPER_HOST}
    profiles: ["prod", "back"]
    environment:
      <<: *defaultEnvs
      MSEVENT_URL: ${MSEVENT_URL}
      SERVICE_NAME: ${MSSCRAPER_HOST}
      TLS_METRO_URL: ${MSSCRAPER_TLS_METRO_URL}
      TLS_LIMIT: ${MSSCRAPER_TLS_LIMIT}
    networks:
      - internal    
    healthcheck: *healthcheck
    logging: *logging


  admin:
    image: ${REPO_URL}:${REPO_PORT}/${APP_NAME}_admin:${APP_VERSION}
    build:
      context: ${PWD}/front/admin
      dockerfile: dockerfile.prod
      <<: *secretArgs
      args:
        <<: *defaultArgs
        NODE_VERSION: ${ADMIN_NODE_VERSION}
        NGINX_VERSION: ${NGINX_VERSION}
    secrets: *secretMount
    container_name: ${ADMIN_HOST}
    hostname: ${ADMIN_HOST}
    profiles: ["admin"]
    networks:
      - internal
    logging: *logging

  mobile:
    image: ${REPO_URL}:${REPO_PORT}/${APP_NAME}_mobile:${APP_VERSION}
    build:
      context: ${PWD}/front/mobile
      dockerfile: dockerfile.prod
      <<: *secretArgs
      args:
        <<: *defaultArgs
        NODE_VERSION: ${MOBILE_NODE_VERSION}
        NGINX_VERSION: ${NGINX_VERSION}
    secrets: *secretMount
    container_name: ${MOBILE_HOST}
    hostname: ${MOBILE_HOST}
    profiles: ["mobile"]
    networks:
      - internal
    logging: *logging

  web:
    image: ${REPO_URL}:${REPO_PORT}/${APP_NAME}_web:${APP_VERSION}
    build:
      context: ${PWD}/front/web
      dockerfile: dockerfile.prod
      <<: *secretArgs
      args:
        <<: *defaultArgs
        NODE_VERSION: ${WEB_NODE_VERSION}
        NGINX_VERSION: ${NGINX_VERSION}
    secrets: *secretMount
    container_name: ${WEB_HOST}
    hostname: ${WEB_HOST}
    profiles: ["web"]
    networks:
      - internal
    logging: *logging
      
networks:
  internal:
    name: ${APP_NAME}-external-${ENV_NAME}
    driver: bridge 
  external:
    name: ${APP_NAME}-internal-${ENV_NAME}
    driver: bridge


secrets:
  apk_repository:
    environment: APK_REPOSITORY
  apt_repository:
    environment: APT_REPOSITORY
  npmrc:
    environment: NPMRC


volumes:
  postgres_data:
    driver: local
  postgis_data:
    driver: local
  user_assets:
    driver: local
  mail_assets:
    driver: local
  event_assets:
    driver: local