name: ${APP_NAME}

x-logging-conf: &logging
  driver: "json-file"
  options: 
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

x-service-healthcheck: &healthcheck
  test: ["CMD", "node", "/usr/src/app/node_modules/health/test.js"]
  interval: 10s
  timeout: 5s
  retries: 5

# dockerfile mount during build
x-secret-args: &secretArgs
  secrets:
    - apt_repository
    - apk_repository
    - npmrc

# mount for run
x-secret-mount: &secretMount
  - source: npmrc
    target: /home/user/.npmrc

x-default-args: &defaultArgs
  UID: ${UID}
  GID: ${GID}
  TZ: ${TZ}
  HOME_PATH: ${HOME_PATH}

x-default-envs: &defaultEnvs
  PORT: ${DEFAULT_PORT}
  TZ: ${TZ}

x-resources-limits:
  # - &cadvisorLimit
  #   cpus: ${CADVISOR_LIMIT_CPUS}
  #   mem_limit: ${CADVISOR_LIMIT_MEM}
  # - &prometheusLimit
  #   cpus: ${PROMETHEUS_LIMIT_CPUS}
  #   mem_limit: ${PROMETHEUS_LIMIT_MEM}
  - &grafanaLimit
    cpus: ${GRAFANA_LIMIT_CPUS}
    mem_limit: ${GRAFANA_LIMIT_MEM}
  # - &promtailLimit
  #   cpus: ${PROMTAIL_LIMIT_CPUS}
  #   mem_limit: ${PROMTAIL_LIMIT_MEM}
  - &lokiLimit
    cpus: ${LOKI_LIMIT_CPUS}
    mem_limit: ${LOKI_LIMIT_MEM}

x-labels-conf: &labels
  logging: alloy
  logging_project: ${APP_NAME}
  logging_env: ${ENV_NAME}

services:

  # cadvisor:
  #   image: ${CADVISOR_VERSION}
  #   container_name: ${CADVISOR_HOST}
  #   profiles: ["monitor"]
  #   restart: unless-stopped
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #     - /dev/disk/:/dev/disk:ro
  #     - /cgroup:/cgroup:ro
  #   # ports:
  #   #   - "8005:8080"
  #   networks:
  #     - mon
  #   <<: *cadvisorLimit


  # prometheus:
  #   image: ${PROMETHEUS_VERSION}
  #   container_name: ${PROMETHEUS_HOST}
  #   hostname:  ${PROMETHEUS_HOST}
  #   profiles: ["monitor"]
  #   restart: unless-stopped
  #   environment:
  #     # PG_EXPORTER_HOST: ${PG_EXPORTER_HOST}
  #     CADVISOR_HOST: ${CADVISOR_HOST}
  #     PROMETHEUS_HOST: ${PROMETHEUS_HOST}
  #     NODE_EXPORTER_HOST: ${NODE_EXPORTER_HOST}
  #   volumes:
  #     - ${PWD}/mon/prometheus/config:/etc/prometheus
  #     - ${PWD}/mon/prometheus/data:/var/lib/prometheus/data
  #   networks:
  #     - mon
  #   depends_on:
  #     - cadvisor
  #     - postgres_exporter
  #   command: 
  #     - "--config.file=/etc/prometheus/prometheus.yml"
  #     - "--web.external-url=/prometheus/"
  #     - "--web.route-prefix=/"
  #   labels:
  #     - "traefik.enable=true"
  #     - "stack.name=${STACK_NAME}"
  #     - "traefik.http.routers.prometheus.rule=PathPrefix(`/prometheus`)"
  #     - "traefik.http.routers.prometheus.entrypoints=web"
  #     - "traefik.http.routers.prometheus.service=prometheus"
  #     - "traefik.http.routers.prometheus.middlewares=prometheus"
  #     - "traefik.http.services.prometheus.loadbalancer.server.port=${PROMETHEUS_PORT}"
  #     - "traefik.http.middlewares.prometheus.stripprefix.prefixes=/prometheus"
  #   <<: *prometheusLimit

  alloy:
    image: grafana/alloy:latest
    hostname: sdc-demo-alloy
    environment:
      PG_EXPORTER_HOST: pg_exporter:9187
      PROJECT_NAME: ${PROJECT_NAME}
      MONITORING_URL: ${MONITORING_URL}
    ports:
      - "12346:12345"
    volumes:
      - "./alloy/config.alloy:/etc/alloy/config.alloy"
    networks:
      - project
      - monitoring
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--stability.level=public-preview",
      "/etc/alloy/config.alloy",
    ]


volumes:
  grafana-storage:
    name: grafana-storage
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /projects/mon/grafana
  mimir-storage:
    name: mimir-storage
    driver: local
  loki-storage:
    name: ${APP_NAME}-loki-volume
    driver: local
  # tempo-storage:
  #   name: ${APP_NAME}-tempo-volume
  #   driver: local
  # prometheus:
  #   name: prometheus-volume
  #   driver: local


networks:
  monitoring:
    name: monitoring-external-network-${ENV_NAME}
    driver: bridge 
    external: true
