name: ${APP_NAME}

services:
  gatelin:
    build:
      context: ${PWD}
      dockerfile: dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        TZ: ${TZ}
        NODE_VERSION: ${NODE_VERSION}
        NODE_ENV: ${NODE_ENV}
    image: gatelin:${NODE_ENV:-development}
    container_name: ${GATELIN_HOST}
    # hostname: ${GATELIN_HOST}
    volumes:
      - gateway_node_modules:/usr/src/app/node_modules
