import { readFileSync } from "node:fs";
import { resolve } from "node:path";

export type E2eCredentials = {
  email: string;
  password: string;
};

function findPassword(node: unknown, email: string): string | undefined {
  if (!node || typeof node !== "object") {
    return undefined;
  }

  if (Array.isArray(node)) {
    for (const item of node) {
      const found = findPassword(item, email);
      if (found) return found;
    }
    return undefined;
  }

  const record = node as Record<string, unknown>;
  if (record.email === email && typeof record.pwd === "string") {
    return record.pwd;
  }

  for (const value of Object.values(record)) {
    const found = findPassword(value, email);
    if (found) return found;
  }

  return undefined;
}

/**
 * Resolves login credentials for e2e.
 * Prefer E2E_EMAIL / E2E_PASSWORD; otherwise read the password generated by
 * `./scripts/setup-mocks.sh` from swagger/src/gatelin.openapi.json.
 */
export function getAdminCredentials(
  email = process.env.E2E_EMAIL ?? "admin@example.com",
): E2eCredentials {
  if (process.env.E2E_PASSWORD) {
    return { email, password: process.env.E2E_PASSWORD };
  }

  const openapiPath = resolve(
    __dirname,
    "../../../swagger/src/gatelin.openapi.json",
  );
  const openapi = JSON.parse(readFileSync(openapiPath, "utf8")) as unknown;
  const password = findPassword(openapi, email);

  if (!password) {
    throw new Error(
      `No password found for ${email}. Set E2E_PASSWORD or run ./scripts/setup-mocks.sh.`,
    );
  }

  return { email, password };
}
