ARG NODE_VERSION
ARG NGINX_VERSION
FROM node:${NODE_VERSION} As build

# change apk repos
RUN rm /etc/apk/repositories
RUN --mount=type=secret,id=apk_repository,target=/etc/apk/repositories,required=true apk update \
    && apk add tzdata 

ARG TZ
ENV TZ=${TZ}
# RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Create a new basic user 
ARG UID
ARG GID
RUN deluser --remove-home node && addgroup -S usergroup -g ${GID} && adduser -G usergroup -S user -u ${UID}
USER user

ARG NPMRC_PATH
RUN --mount=type=secret,id=npmrc,target=${NPMRC_PATH},required=true,uid=${UID}

ENV NODE_ENV=production

WORKDIR /usr/src/app
COPY --chown=user:usergroup . .

RUN npm i -no-progress --ignore-scripts --production --omit=optional --loglevel=error --no-fund \
    && npm i @angular/cli -no-progress --ignore-scripts --omit=optional --loglevel=error --no-fund

ENV PATH /usr/src/app/node_modules/.bin:$PATH

RUN npm run build:prod

############
### prod ###
############

FROM nginx:${NGINX_VERSION}

RUN rm -f /etc/nginx/conf.d/*.conf
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
# copy artifact build from the 'build environment'
COPY --from=build /usr/src/app/dist/ /usr/share/nginx/html