ARG NODE_VERSION=24.11.0-alpine3.22
ARG NGINX_VERSION=1.27.5-alpine

FROM node:${NODE_VERSION} AS build

RUN apk add --no-cache tzdata

ARG TZ=UTC
ENV TZ=${TZ}

ARG UID=1000
ARG GID=1000
RUN addgroup -S appgroup -g ${GID} \
  && adduser -S -G appgroup -u ${UID} appuser

WORKDIR /usr/src/app
ARG UID=1000
# ARG NPMRC_PATH=/home/appuser/.npmrc
# RUN --mount=type=secret,id=npmrc,target=${NPMRC_PATH},required=true,uid=${UID} \
#   npm install --ignore-scripts --no-fund --no-audit --loglevel=error
COPY --chown=appuser:appgroup package*.json ./
RUN npm install --ignore-scripts --no-fund --no-audit --loglevel=error

COPY --chown=appuser:appgroup . .
USER appuser
RUN npm run build:prod

FROM nginx:${NGINX_VERSION}

RUN rm -f /etc/nginx/conf.d/*.conf
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/dist/ /usr/share/nginx/html