ARG NODE_VERSION
FROM node:${NODE_VERSION} As build

ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}

# change apk repos
# RUN rm /etc/apk/repositories
# RUN --mount=type=secret,id=apk_repository,target=/etc/apk/repositories,required=true 
RUN apk update && apk add postgresql-client tzdata 

ARG TZ
ENV TZ=${TZ}

# Create a new basic user 
ARG UID
ARG GID
RUN deluser --remove-home node && addgroup -S usergroup -g ${GID} && adduser -G usergroup -S user -u ${UID}
USER user

# ARG HOME_PATH
# ARG UID
# RUN --mount=type=secret,id=npmrc,target=${HOME_PATH}.npmrc,required=true,uid=${UID}

# COPY common/libs/packs/ /usr/src/libs/packs
# COPY common/rollup/ /usr/src/rollup

ARG FOLDER
WORKDIR /opt/docker-entrypoint
COPY --chown=user:usergroup ${FOLDER}/assets/public/ ./public/
COPY --chown=user:usergroup ${FOLDER}/assets/templates/ ./templates/
COPY --chown=user:usergroup ${FOLDER}/sql/struct.sql ${FOLDER}/sql/data.sql ./sql/
COPY --chown=user:usergroup --chmod=500 common/entrypoint.sh .

# WORKDIR /usr/src/app
# COPY --chown=user:usergroup ${FOLDER}/package*.json ./
COPY --chown=user:usergroup ${FOLDER}/dist/ /usr/src/app/

# RUN npm i --loglevel=error --ignore-scripts --no-fund  --no-audit --production

# RUN npm run build

############
### prod ###
############

# FROM node:${NODE_VERSION}

# ENV NODE_ENV=${NODE_ENV}

# # change apk repos
# RUN rm /etc/apk/repositories
# RUN --mount=type=secret,id=apk_repository,target=/etc/apk/repositories,required=true apk update \
#     && apk add postgresql-client tzdata 

# ARG TZ
# ENV TZ=${TZ}

# # Create a new basic user 
# ARG UID
# ARG GID
# RUN deluser --remove-home node && addgroup -S usergroup -g ${GID} && adduser -G usergroup -S user -u ${UID}
# USER user

# COPY --from=build --chown=user:usergroup /usr/src/app/dist/ /usr/src/app/dist

# WORKDIR /opt/docker-entrypoint
# ARG FOLDER
# COPY --chown=user:usergroup ${FOLDER}/assets/public/ ./public/
# COPY --chown=user:usergroup ${FOLDER}/assets/templates/ ./templates/
# COPY --chown=user:usergroup ${FOLDER}/sql/struct.sql ${FOLDER}/sql/data.sql ./sql/
# COPY --chown=user:usergroup --chmod=500 common/entrypoint.sh .

ENTRYPOINT ["sh","/opt/docker-entrypoint/entrypoint.sh"]
CMD [ "node", "./app.js" ]