ARG NODE_VERSION
FROM node:${NODE_VERSION}

LABEL org.opencontainers.image.description="Gatelin documentation site (VitePress, development)"

ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}

# install tzdata from default Alpine repos before replacing them
RUN apk add --no-cache tzdata

ARG TZ
ENV TZ=${TZ}

ARG UID
ARG GID
RUN deluser --remove-home node && addgroup -S usergroup -g ${GID} && adduser -G usergroup -S user -u ${UID}
USER user

ARG NPMRC_PATH
RUN --mount=type=secret,id=npmrc,target=${NPMRC_PATH},required=true,uid=${UID}

WORKDIR /usr/src/app
COPY --chown=user:usergroup --chmod=640 package*.json ./

RUN npm i --loglevel=error --ignore-scripts --no-fund

CMD [ "node", "--run", "dev" ]
