ARG NODE_VERSION=24.11.0-alpine3.22
ARG NGINX_VERSION=1.27.5-alpine

FROM node:${NODE_VERSION} AS build
WORKDIR /usr/src/app
ARG UID=1000
# ARG NPMRC_PATH=/root/.npmrc
# RUN --mount=type=secret,id=npmrc,target=${NPMRC_PATH},required=true,uid=${UID} \
#   npm install --ignore-scripts --no-fund --no-audit --loglevel=error

COPY package*.json ./
RUN npm install --ignore-scripts --no-fund --no-audit --loglevel=error

COPY . .
RUN npm run build

FROM nginx:${NGINX_VERSION}

RUN rm -f /etc/nginx/conf.d/*.conf
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/docs/.vitepress/dist /usr/share/nginx/html/docs
